package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Actestado generated by hbm2java
 */
@Entity
@Table(name = "actestado")
public class Actestado implements java.io.Serializable {

	private String codestado;
	private String descripcion;
	private Set<Estadoactivacion> estadoactivacions = new HashSet<Estadoactivacion>(
			0);
	private Set<Activacion> activacions = new HashSet<Activacion>(0);

	public Actestado() {
	}

	public Actestado(String codestado) {
		this.codestado = codestado;
	}

	public Actestado(String codestado, String descripcion,
			Set<Estadoactivacion> estadoactivacions, Set<Activacion> activacions) {
		this.codestado = codestado;
		this.descripcion = descripcion;
		this.estadoactivacions = estadoactivacions;
		this.activacions = activacions;
	}

	@Id
	@Column(name = "codestado", unique = true, nullable = false, length = 2)
	@NotNull
	@Length(max = 2)
	public String getCodestado() {
		return this.codestado;
	}

	public void setCodestado(String codestado) {
		this.codestado = codestado;
	}

	@Column(name = "descripcion", length = 50)
	@Length(max = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "actestado")
	public Set<Estadoactivacion> getEstadoactivacions() {
		return this.estadoactivacions;
	}

	public void setEstadoactivacions(Set<Estadoactivacion> estadoactivacions) {
		this.estadoactivacions = estadoactivacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "actestado")
	public Set<Activacion> getActivacions() {
		return this.activacions;
	}

	public void setActivacions(Set<Activacion> activacions) {
		this.activacions = activacions;
	}

}
