package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Arrastrador generated by hbm2java
 */
@Entity
@Table(name = "arrastrador")
public class Arrastrador implements java.io.Serializable {

	private String documento;
	private Personal personal;
	private Set<Promotor> promotors = new HashSet<Promotor>(0);

	public Arrastrador() {
	}

	public Arrastrador(Personal personal) {
		this.personal = personal;
	}

	public Arrastrador(Personal personal, Set<Promotor> promotors) {
		this.personal = personal;
		this.promotors = promotors;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "personal"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "documento", unique = true, nullable = false, length = 15)
	@Length(max = 15)
	public String getDocumento() {
		return this.documento;
	}

	public void setDocumento(String documento) {
		this.documento = documento;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	@NotNull
	@Length(max = 15)
	public Personal getPersonal() {
		return this.personal;
	}

	public void setPersonal(Personal personal) {
		this.personal = personal;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "arrastrador")
	public Set<Promotor> getPromotors() {
		return this.promotors;
	}

	public void setPromotors(Set<Promotor> promotors) {
		this.promotors = promotors;
	}

}
