package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * AuditViaje generated by hbm2java
 */
@Entity
@Table(name = "audit_viaje")
public class AuditViaje implements java.io.Serializable {

	private AuditViajeId id;

	public AuditViaje() {
	}

	public AuditViaje(AuditViajeId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "consecutivo", column = @Column(name = "consecutivo", nullable = false)),
			@AttributeOverride(name = "fechainicio", column = @Column(name = "fechainicio", length = 13)),
			@AttributeOverride(name = "fechafin", column = @Column(name = "fechafin", length = 13)),
			@AttributeOverride(name = "cupoinicialviajero", column = @Column(name = "cupoinicialviajero", precision = 5, scale = 0)),
			@AttributeOverride(name = "cupoinicialinternet", column = @Column(name = "cupoinicialinternet", precision = 5, scale = 0)),
			@AttributeOverride(name = "cupoviajero", column = @Column(name = "cupoviajero", precision = 8, scale = 0)),
			@AttributeOverride(name = "cupointernet", column = @Column(name = "cupointernet", precision = 8, scale = 0)),
			@AttributeOverride(name = "cedulatarjetahabiente", column = @Column(name = "cedulatarjetahabiente", length = 15)),
			@AttributeOverride(name = "fechamod", column = @Column(name = "fechamod", length = 22)),
			@AttributeOverride(name = "usuariomod", column = @Column(name = "usuariomod", length = 20)) })
	@NotNull
	public AuditViajeId getId() {
		return this.id;
	}

	public void setId(AuditViajeId id) {
		this.id = id;
	}

}
