package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * AuditUsuario generated by hbm2java
 */
@Entity
@Table(name = "audit_usuario")
public class AuditUsuario implements java.io.Serializable {

	private AuditUsuarioId id;

	public AuditUsuario() {
	}

	public AuditUsuario(AuditUsuarioId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "usuario", column = @Column(name = "usuario", nullable = false, length = 15)),
			@AttributeOverride(name = "fecha", column = @Column(name = "fecha", nullable = false, length = 29)),
			@AttributeOverride(name = "operacion", column = @Column(name = "operacion")),
			@AttributeOverride(name = "descripcion", column = @Column(name = "descripcion", length = 300)),
			@AttributeOverride(name = "ipcliente", column = @Column(name = "ipcliente", length = 25)) })
	@NotNull
	public AuditUsuarioId getId() {
		return this.id;
	}

	public void setId(AuditUsuarioId id) {
		this.id = id;
	}

}
