package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * AuditTarjetaviaje generated by hbm2java
 */
@Entity
@Table(name = "audit_tarjetaviaje")
public class AuditTarjetaviaje implements java.io.Serializable {

	private AuditTarjetaviajeId id;
	private Viaje viaje;
	private Tarjeta tarjeta;

	public AuditTarjetaviaje() {
	}

	public AuditTarjetaviaje(AuditTarjetaviajeId id, Viaje viaje,
			Tarjeta tarjeta) {
		this.id = id;
		this.viaje = viaje;
		this.tarjeta = tarjeta;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "numerotarjeta", column = @Column(name = "numerotarjeta", nullable = false, length = 16)),
			@AttributeOverride(name = "consecutivoviaje", column = @Column(name = "consecutivoviaje", nullable = false)),
			@AttributeOverride(name = "estado", column = @Column(name = "estado", precision = 1, scale = 0)),
			@AttributeOverride(name = "fechamod", column = @Column(name = "fechamod", length = 22)),
			@AttributeOverride(name = "usuariomod", column = @Column(name = "usuariomod", length = 20)) })
	@NotNull
	public AuditTarjetaviajeId getId() {
		return this.id;
	}

	public void setId(AuditTarjetaviajeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "consecutivoviaje", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Viaje getViaje() {
		return this.viaje;
	}

	public void setViaje(Viaje viaje) {
		this.viaje = viaje;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "numerotarjeta", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Tarjeta getTarjeta() {
		return this.tarjeta;
	}

	public void setTarjeta(Tarjeta tarjeta) {
		this.tarjeta = tarjeta;
	}

}
