package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;

/**
 * Banner generated by hbm2java
 */
@Entity
@Table(name = "banner")
public class Banner implements java.io.Serializable {

	private int consecutivo;
	private String imagen;
	private String caption;
	private Boolean estado;
	private Date fechainicio;
	private Date fechafin;
	private String clase;

	public Banner() {
	}

	public Banner(int consecutivo) {
		this.consecutivo = consecutivo;
	}

	public Banner(int consecutivo, String imagen, String caption,
			Boolean estado, Date fechainicio, Date fechafin, String clase) {
		this.consecutivo = consecutivo;
		this.imagen = imagen;
		this.caption = caption;
		this.estado = estado;
		this.fechainicio = fechainicio;
		this.fechafin = fechafin;
		this.clase = clase;
	}

	@Id
	@Column(name = "consecutivo", unique = true, nullable = false)
	public int getConsecutivo() {
		return this.consecutivo;
	}

	public void setConsecutivo(int consecutivo) {
		this.consecutivo = consecutivo;
	}

	@Column(name = "imagen", length = 30)
	@Length(max = 30)
	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	@Column(name = "caption", length = 250)
	@Length(max = 250)
	public String getCaption() {
		return this.caption;
	}

	public void setCaption(String caption) {
		this.caption = caption;
	}

	@Column(name = "estado")
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechainicio", length = 13)
	public Date getFechainicio() {
		return this.fechainicio;
	}

	public void setFechainicio(Date fechainicio) {
		this.fechainicio = fechainicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechafin", length = 13)
	public Date getFechafin() {
		return this.fechafin;
	}

	public void setFechafin(Date fechafin) {
		this.fechafin = fechafin;
	}

	@Column(name = "clase", length = 20)
	@Length(max = 20)
	public String getClase() {
		return this.clase;
	}

	public void setClase(String clase) {
		this.clase = clase;
	}

}
