package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;

/**
 * Bloqueotarjeta generated by hbm2java
 */
@Entity
@Table(name = "bloqueotarjeta")
public class Bloqueotarjeta implements java.io.Serializable {

	private int secuencia;
	private String numerotarjeta;
	private Integer consecutivo;
	private String observacion;
	private Date fecha;

	public Bloqueotarjeta() {
	}

	public Bloqueotarjeta(int secuencia) {
		this.secuencia = secuencia;
	}

	public Bloqueotarjeta(int secuencia, String numerotarjeta,
			Integer consecutivo, String observacion, Date fecha) {
		this.secuencia = secuencia;
		this.numerotarjeta = numerotarjeta;
		this.consecutivo = consecutivo;
		this.observacion = observacion;
		this.fecha = fecha;
	}

	@Id
	@Column(name = "secuencia", unique = true, nullable = false)
	public int getSecuencia() {
		return this.secuencia;
	}

	public void setSecuencia(int secuencia) {
		this.secuencia = secuencia;
	}

	@Column(name = "numerotarjeta", length = 16)
	@Length(max = 16)
	public String getNumerotarjeta() {
		return this.numerotarjeta;
	}

	public void setNumerotarjeta(String numerotarjeta) {
		this.numerotarjeta = numerotarjeta;
	}

	@Column(name = "consecutivo")
	public Integer getConsecutivo() {
		return this.consecutivo;
	}

	public void setConsecutivo(Integer consecutivo) {
		this.consecutivo = consecutivo;
	}

	@Column(name = "observacion")
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", length = 29)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
