package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.NotNull;

/**
 * Calendario generated by hbm2java
 */
@Entity
@Table(name = "calendario")
public class Calendario implements java.io.Serializable {

	private Date fecha;
	private short anio;
	private short mes;
	private short dia;
	private short trimestre;
	private short diaDeSemana;
	private short diaDeAnio;
	private short semanaDeAnio;

	public Calendario() {
	}

	public Calendario(Date fecha, short anio, short mes, short dia,
			short trimestre, short diaDeSemana, short diaDeAnio,
			short semanaDeAnio) {
		this.fecha = fecha;
		this.anio = anio;
		this.mes = mes;
		this.dia = dia;
		this.trimestre = trimestre;
		this.diaDeSemana = diaDeSemana;
		this.diaDeAnio = diaDeAnio;
		this.semanaDeAnio = semanaDeAnio;
	}

	@Id
	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", unique = true, nullable = false, length = 13)
	@NotNull
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "anio", nullable = false)
	public short getAnio() {
		return this.anio;
	}

	public void setAnio(short anio) {
		this.anio = anio;
	}

	@Column(name = "mes", nullable = false)
	public short getMes() {
		return this.mes;
	}

	public void setMes(short mes) {
		this.mes = mes;
	}

	@Column(name = "dia", nullable = false)
	public short getDia() {
		return this.dia;
	}

	public void setDia(short dia) {
		this.dia = dia;
	}

	@Column(name = "trimestre", nullable = false)
	public short getTrimestre() {
		return this.trimestre;
	}

	public void setTrimestre(short trimestre) {
		this.trimestre = trimestre;
	}

	@Column(name = "dia_de_semana", nullable = false)
	public short getDiaDeSemana() {
		return this.diaDeSemana;
	}

	public void setDiaDeSemana(short diaDeSemana) {
		this.diaDeSemana = diaDeSemana;
	}

	@Column(name = "dia_de_anio", nullable = false)
	public short getDiaDeAnio() {
		return this.diaDeAnio;
	}

	public void setDiaDeAnio(short diaDeAnio) {
		this.diaDeAnio = diaDeAnio;
	}

	@Column(name = "semana_de_anio", nullable = false)
	public short getSemanaDeAnio() {
		return this.semanaDeAnio;
	}

	public void setSemanaDeAnio(short semanaDeAnio) {
		this.semanaDeAnio = semanaDeAnio;
	}

}
