package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Cne generated by hbm2java
 */
@Entity
@Table(name = "cne")
public class Cne implements java.io.Serializable {

	private String cedula;
	private String nacionalidad;
	private String primerApellido;
	private String segundoApellido;
	private String primerNombre;
	private String segundoNombre;
	private String estado;
	private String codCentro;

	public Cne() {
	}

	public Cne(String cedula) {
		this.cedula = cedula;
	}

	public Cne(String cedula, String nacionalidad, String primerApellido,
			String segundoApellido, String primerNombre, String segundoNombre,
			String estado, String codCentro) {
		this.cedula = cedula;
		this.nacionalidad = nacionalidad;
		this.primerApellido = primerApellido;
		this.segundoApellido = segundoApellido;
		this.primerNombre = primerNombre;
		this.segundoNombre = segundoNombre;
		this.estado = estado;
		this.codCentro = codCentro;
	}

	@Id
	@Column(name = "cedula", unique = true, nullable = false, length = 15)
	@NotNull
	@Length(max = 15)
	public String getCedula() {
		return this.cedula;
	}

	public void setCedula(String cedula) {
		this.cedula = cedula;
	}

	@Column(name = "nacionalidad", length = 2)
	@Length(max = 2)
	public String getNacionalidad() {
		return this.nacionalidad;
	}

	public void setNacionalidad(String nacionalidad) {
		this.nacionalidad = nacionalidad;
	}

	@Column(name = "primer_apellido", length = 50)
	@Length(max = 50)
	public String getPrimerApellido() {
		return this.primerApellido;
	}

	public void setPrimerApellido(String primerApellido) {
		this.primerApellido = primerApellido;
	}

	@Column(name = "segundo_apellido", length = 50)
	@Length(max = 50)
	public String getSegundoApellido() {
		return this.segundoApellido;
	}

	public void setSegundoApellido(String segundoApellido) {
		this.segundoApellido = segundoApellido;
	}

	@Column(name = "primer_nombre", length = 50)
	@Length(max = 50)
	public String getPrimerNombre() {
		return this.primerNombre;
	}

	public void setPrimerNombre(String primerNombre) {
		this.primerNombre = primerNombre;
	}

	@Column(name = "segundo_nombre", length = 50)
	@Length(max = 50)
	public String getSegundoNombre() {
		return this.segundoNombre;
	}

	public void setSegundoNombre(String segundoNombre) {
		this.segundoNombre = segundoNombre;
	}

	@Column(name = "estado", length = 20)
	@Length(max = 20)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "cod_centro", length = 12)
	@Length(max = 12)
	public String getCodCentro() {
		return this.codCentro;
	}

	public void setCodCentro(String codCentro) {
		this.codCentro = codCentro;
	}

}
