package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Cnedireccion generated by hbm2java
 */
@Entity
@Table(name = "cnedireccion")
public class Cnedireccion implements java.io.Serializable {

	private String codCentro;
	private String tipo;
	private String codEstado;
	private String codMunicipio;
	private String codParroquia;
	private String nombreCentro;
	private String direccionCentro;
	private String centroNuevo;

	public Cnedireccion() {
	}

	public Cnedireccion(String codCentro) {
		this.codCentro = codCentro;
	}

	public Cnedireccion(String codCentro, String tipo, String codEstado,
			String codMunicipio, String codParroquia, String nombreCentro,
			String direccionCentro, String centroNuevo) {
		this.codCentro = codCentro;
		this.tipo = tipo;
		this.codEstado = codEstado;
		this.codMunicipio = codMunicipio;
		this.codParroquia = codParroquia;
		this.nombreCentro = nombreCentro;
		this.direccionCentro = direccionCentro;
		this.centroNuevo = centroNuevo;
	}

	@Id
	@Column(name = "cod_centro", unique = true, nullable = false, length = 10)
	@NotNull
	@Length(max = 10)
	public String getCodCentro() {
		return this.codCentro;
	}

	public void setCodCentro(String codCentro) {
		this.codCentro = codCentro;
	}

	@Column(name = "tipo", length = 3)
	@Length(max = 3)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "cod_estado", length = 3)
	@Length(max = 3)
	public String getCodEstado() {
		return this.codEstado;
	}

	public void setCodEstado(String codEstado) {
		this.codEstado = codEstado;
	}

	@Column(name = "cod_municipio", length = 3)
	@Length(max = 3)
	public String getCodMunicipio() {
		return this.codMunicipio;
	}

	public void setCodMunicipio(String codMunicipio) {
		this.codMunicipio = codMunicipio;
	}

	@Column(name = "cod_parroquia", length = 3)
	@Length(max = 3)
	public String getCodParroquia() {
		return this.codParroquia;
	}

	public void setCodParroquia(String codParroquia) {
		this.codParroquia = codParroquia;
	}

	@Column(name = "nombre_centro", length = 300)
	@Length(max = 300)
	public String getNombreCentro() {
		return this.nombreCentro;
	}

	public void setNombreCentro(String nombreCentro) {
		this.nombreCentro = nombreCentro;
	}

	@Column(name = "direccion_centro", length = 300)
	@Length(max = 300)
	public String getDireccionCentro() {
		return this.direccionCentro;
	}

	public void setDireccionCentro(String direccionCentro) {
		this.direccionCentro = direccionCentro;
	}

	@Column(name = "centro_nuevo", length = 15)
	@Length(max = 15)
	public String getCentroNuevo() {
		return this.centroNuevo;
	}

	public void setCentroNuevo(String centroNuevo) {
		this.centroNuevo = centroNuevo;
	}

}
