package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.NotNull;

/**
 * Comisionhistorico generated by hbm2java
 */
@Entity
@Table(name = "comisionhistorico")
public class Comisionhistorico implements java.io.Serializable {

	private ComisionhistoricoId id;
	private Personal personal;
	private Date fechafin;
	private BigDecimal valor;

	public Comisionhistorico() {
	}

	public Comisionhistorico(ComisionhistoricoId id, Personal personal) {
		this.id = id;
		this.personal = personal;
	}

	public Comisionhistorico(ComisionhistoricoId id, Personal personal,
			Date fechafin, BigDecimal valor) {
		this.id = id;
		this.personal = personal;
		this.fechafin = fechafin;
		this.valor = valor;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "documento", column = @Column(name = "documento", nullable = false, length = 15)),
			@AttributeOverride(name = "fechainicio", column = @Column(name = "fechainicio", nullable = false, length = 29)) })
	@NotNull
	public ComisionhistoricoId getId() {
		return this.id;
	}

	public void setId(ComisionhistoricoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "documento", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Personal getPersonal() {
		return this.personal;
	}

	public void setPersonal(Personal personal) {
		this.personal = personal;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechafin", length = 29)
	public Date getFechafin() {
		return this.fechafin;
	}

	public void setFechafin(Date fechafin) {
		this.fechafin = fechafin;
	}

	@Column(name = "valor", precision = 5, scale = 3)
	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

}
