package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * CuentapromotorId generated by hbm2java
 */
@Embeddable
public class CuentapromotorId implements java.io.Serializable {

	private String numcuenta;
	private String documento;

	public CuentapromotorId() {
	}

	public CuentapromotorId(String numcuenta, String documento) {
		this.numcuenta = numcuenta;
		this.documento = documento;
	}

	@Column(name = "numcuenta", nullable = false, length = 25)
	@NotNull
	@Length(max = 25)
	public String getNumcuenta() {
		return this.numcuenta;
	}

	public void setNumcuenta(String numcuenta) {
		this.numcuenta = numcuenta;
	}

	@Column(name = "documento", nullable = false, length = 15)
	@NotNull
	@Length(max = 15)
	public String getDocumento() {
		return this.documento;
	}

	public void setDocumento(String documento) {
		this.documento = documento;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CuentapromotorId))
			return false;
		CuentapromotorId castOther = (CuentapromotorId) other;

		return ((this.getNumcuenta() == castOther.getNumcuenta()) || (this
				.getNumcuenta() != null
				&& castOther.getNumcuenta() != null && this.getNumcuenta()
				.equals(castOther.getNumcuenta())))
				&& ((this.getDocumento() == castOther.getDocumento()) || (this
						.getDocumento() != null
						&& castOther.getDocumento() != null && this
						.getDocumento().equals(castOther.getDocumento())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getNumcuenta() == null ? 0 : this.getNumcuenta().hashCode());
		result = 37 * result
				+ (getDocumento() == null ? 0 : this.getDocumento().hashCode());
		return result;
	}

}
