package org.domain.monedaliquidacion.entity;

// Generated 31/01/2012 05:27:17 AM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Deducciones generated by hbm2java
 */
@Entity
@Table(name = "deducciones", schema = "public")
public class Deducciones implements java.io.Serializable {

	private DeduccionesId id;
	private Transaccion transaccion;
	private String descripcion;
	private BigDecimal valor;

	public Deducciones() {
	}

	public Deducciones(DeduccionesId id, Transaccion transaccion) {
		this.id = id;
		this.transaccion = transaccion;
	}

	public Deducciones(DeduccionesId id, Transaccion transaccion,
			BigDecimal valor) {
		this.id = id;
		this.transaccion = transaccion;
		this.valor = valor;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "consecutivo", column = @Column(name = "consecutivo", nullable = false)),
			@AttributeOverride(name = "descripcion", column = @Column(name = "descripcion", nullable = false, length = 30)) })
	@NotNull
	public DeduccionesId getId() {
		return this.id;
	}

	public void setId(DeduccionesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "consecutivo", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Transaccion getTransaccion() {
		return this.transaccion;
	}

	public void setTransaccion(Transaccion transaccion) {
		this.transaccion = transaccion;
	}

	@Column(name = "valor", precision = 7, scale = 0)
	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}
	
	@Column(name = "descripcion", length = 30)
	@Length(max = 30)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
