package org.domain.monedaliquidacion.entity;
// Generated 31/01/2012 05:27:17 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * DeduccionesId generated by hbm2java
 */
@Embeddable
public class DeduccionesId implements java.io.Serializable {

	private int consecutivo;
	private String tipo;

	public DeduccionesId() {
	}

	public DeduccionesId(int consecutivo, String tipo) {
		this.consecutivo = consecutivo;
		this.tipo = tipo;
	}

	@Column(name = "consecutivo", nullable = false)
	public int getConsecutivo() {
		return this.consecutivo;
	}

	public void setConsecutivo(int consecutivo) {
		this.consecutivo = consecutivo;
	}

	@Column(name = "tipo", nullable = false, length = 2)
	@NotNull
	@Length(max = 2)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DeduccionesId))
			return false;
		DeduccionesId castOther = (DeduccionesId) other;

		return (this.getConsecutivo() == castOther.getConsecutivo())
				&& ((this.getTipo() == castOther.getTipo()) || (this
						.getTipo() != null
						&& castOther.getTipo() != null && this
						.getTipo().equals(castOther.getTipo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getConsecutivo();
		result = 37
				* result
				+ (getTipo() == null ? 0 : this.getTipo()
						.hashCode());
		return result;
	}

}
