package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Depositostarjeta generated by hbm2java
 */
@Entity
@Table(name = "depositostarjeta")
public class Depositostarjeta implements java.io.Serializable {

	private int consecutivo;
	private Cuenta cuenta;
	private Tarjeta tarjeta;
	private Date fecha;
	private BigDecimal preciobolivar;
	private BigDecimal valordeposito;
	private String tipodebolivar;
	private BigDecimal depositopesos;
	private String tipodep;
	private Date fechamod;
	private String usuariomod;
	private String asesor;
	private String promotor;

	public Depositostarjeta() {
	}

	public Depositostarjeta(int consecutivo, Tarjeta tarjeta, Date fecha) {
		this.consecutivo = consecutivo;
		this.tarjeta = tarjeta;
		this.fecha = fecha;
	}

	public Depositostarjeta(int consecutivo, Cuenta cuenta, Tarjeta tarjeta,
			Date fecha, BigDecimal preciobolivar, BigDecimal valordeposito,
			String tipodebolivar, BigDecimal depositopesos, String tipodep,
			Date fechamod, String usuariomod, String asesor, String promotor) {
		this.consecutivo = consecutivo;
		this.cuenta = cuenta;
		this.tarjeta = tarjeta;
		this.fecha = fecha;
		this.preciobolivar = preciobolivar;
		this.valordeposito = valordeposito;
		this.tipodebolivar = tipodebolivar;
		this.depositopesos = depositopesos;
		this.tipodep = tipodep;
		this.fechamod = fechamod;
		this.usuariomod = usuariomod;
		this.asesor = asesor;
		this.promotor = promotor;
	}

	@Id
	@Column(name = "consecutivo", unique = true, nullable = false)
	public int getConsecutivo() {
		return this.consecutivo;
	}

	public void setConsecutivo(int consecutivo) {
		this.consecutivo = consecutivo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "numcuenta")
	public Cuenta getCuenta() {
		return this.cuenta;
	}

	public void setCuenta(Cuenta cuenta) {
		this.cuenta = cuenta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "numerotarjeta", nullable = false)
	@NotNull
	public Tarjeta getTarjeta() {
		return this.tarjeta;
	}

	public void setTarjeta(Tarjeta tarjeta) {
		this.tarjeta = tarjeta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 29)
	@NotNull
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "preciobolivar", precision = 4, scale = 1)
	public BigDecimal getPreciobolivar() {
		return this.preciobolivar;
	}

	public void setPreciobolivar(BigDecimal preciobolivar) {
		this.preciobolivar = preciobolivar;
	}

	@Column(name = "valordeposito", precision = 8)
	public BigDecimal getValordeposito() {
		return this.valordeposito;
	}

	public void setValordeposito(BigDecimal valordeposito) {
		this.valordeposito = valordeposito;
	}

	@Column(name = "tipodebolivar", length = 3)
	@Length(max = 3)
	public String getTipodebolivar() {
		return this.tipodebolivar;
	}

	public void setTipodebolivar(String tipodebolivar) {
		this.tipodebolivar = tipodebolivar;
	}

	@Column(name = "depositopesos", precision = 10, scale = 1)
	public BigDecimal getDepositopesos() {
		return this.depositopesos;
	}

	public void setDepositopesos(BigDecimal depositopesos) {
		this.depositopesos = depositopesos;
	}

	@Column(name = "tipodep", length = 1)
	@Length(max = 1)
	public String getTipodep() {
		return this.tipodep;
	}

	public void setTipodep(String tipodep) {
		this.tipodep = tipodep;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechamod", length = 29)
	public Date getFechamod() {
		return this.fechamod;
	}

	public void setFechamod(Date fechamod) {
		this.fechamod = fechamod;
	}

	@Column(name = "usuariomod", length = 15)
	@Length(max = 15)
	public String getUsuariomod() {
		return this.usuariomod;
	}

	public void setUsuariomod(String usuariomod) {
		this.usuariomod = usuariomod;
	}

	@Column(name = "asesor", length = 15)
	@Length(max = 15)
	public String getAsesor() {
		return this.asesor;
	}

	public void setAsesor(String asesor) {
		this.asesor = asesor;
	}

	@Column(name = "promotor", length = 15)
	@Length(max = 15)
	public String getPromotor() {
		return this.promotor;
	}

	public void setPromotor(String promotor) {
		this.promotor = promotor;
	}

}
