package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;

/**
 * Diasemana generated by hbm2java
 */
@Entity
@Table(name = "diasemana")
public class Diasemana implements java.io.Serializable {

	private int codigodia;
	private String nombredia;

	public Diasemana() {
	}

	public Diasemana(int codigodia) {
		this.codigodia = codigodia;
	}

	public Diasemana(int codigodia, String nombredia) {
		this.codigodia = codigodia;
		this.nombredia = nombredia;
	}

	@Id
	@Column(name = "codigodia", unique = true, nullable = false)
	public int getCodigodia() {
		return this.codigodia;
	}

	public void setCodigodia(int codigodia) {
		this.codigodia = codigodia;
	}

	@Column(name = "nombredia", length = 15)
	@Length(max = 15)
	public String getNombredia() {
		return this.nombredia;
	}

	public void setNombredia(String nombredia) {
		this.nombredia = nombredia;
	}

}
