package org.domain.monedaliquidacion.entity;

// Generated 27/04/2015 11:47:31 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * Erroringresocadivi generated by hbm2java
 */
@Entity
@Table(name = "erroringresocadivi")
public class Erroringresocadivi implements java.io.Serializable {

	private ErroringresocadiviId id;
	private Activacion activacion;

	public Erroringresocadivi() {
	}

	public Erroringresocadivi(ErroringresocadiviId id, Activacion activacion) {
		this.id = id;
		this.activacion = activacion;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "consecutivo", column = @Column(name = "consecutivo", nullable = false)),
			@AttributeOverride(name = "fecha", column = @Column(name = "fecha", nullable = false, length = 22)) })
	@NotNull
	public ErroringresocadiviId getId() {
		return this.id;
	}

	public void setId(ErroringresocadiviId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "consecutivo", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Activacion getActivacion() {
		return this.activacion;
	}

	public void setActivacion(Activacion activacion) {
		this.activacion = activacion;
	}

}
