package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * EstablecimientoprecioId generated by hbm2java
 */
@Embeddable
public class EstablecimientoprecioId implements java.io.Serializable {

	private String codigounico;
	private Date fechainicio;

	public EstablecimientoprecioId() {
	}

	public EstablecimientoprecioId(String codigounico, Date fechainicio) {
		this.codigounico = codigounico;
		this.fechainicio = fechainicio;
	}

	@Column(name = "codigounico", nullable = false, length = 8)
	@NotNull
	@Length(max = 8)
	public String getCodigounico() {
		return this.codigounico;
	}

	public void setCodigounico(String codigounico) {
		this.codigounico = codigounico;
	}

	@Column(name = "fechainicio", nullable = false, length = 22)
	@NotNull
	public Date getFechainicio() {
		return this.fechainicio;
	}

	public void setFechainicio(Date fechainicio) {
		this.fechainicio = fechainicio;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EstablecimientoprecioId))
			return false;
		EstablecimientoprecioId castOther = (EstablecimientoprecioId) other;

		return ((this.getCodigounico() == castOther.getCodigounico()) || (this
				.getCodigounico() != null
				&& castOther.getCodigounico() != null && this.getCodigounico()
				.equals(castOther.getCodigounico())))
				&& ((this.getFechainicio() == castOther.getFechainicio()) || (this
						.getFechainicio() != null
						&& castOther.getFechainicio() != null && this
						.getFechainicio().equals(castOther.getFechainicio())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCodigounico() == null ? 0 : this.getCodigounico()
						.hashCode());
		result = 37
				* result
				+ (getFechainicio() == null ? 0 : this.getFechainicio()
						.hashCode());
		return result;
	}

}
