package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Estadoactivacion generated by hbm2java
 */
@Entity
@Table(name = "estadoactivacion")
public class Estadoactivacion implements java.io.Serializable {

	private EstadoactivacionId id;
	private Activacion activacion;
	private Actestado actestado;
	private String observacion;

	public Estadoactivacion() {
	}

	public Estadoactivacion(EstadoactivacionId id, Activacion activacion,
			Actestado actestado) {
		this.id = id;
		this.activacion = activacion;
		this.actestado = actestado;
	}

	public Estadoactivacion(EstadoactivacionId id, Activacion activacion,
			Actestado actestado, String observacion) {
		this.id = id;
		this.activacion = activacion;
		this.actestado = actestado;
		this.observacion = observacion;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "consecutivo", column = @Column(name = "consecutivo", nullable = false)),
			@AttributeOverride(name = "estado", column = @Column(name = "estado", nullable = false, length = 2)),
			@AttributeOverride(name = "fecha", column = @Column(name = "fecha", nullable = false, length = 29)) })
	@NotNull
	public EstadoactivacionId getId() {
		return this.id;
	}

	public void setId(EstadoactivacionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "consecutivo", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Activacion getActivacion() {
		return this.activacion;
	}

	public void setActivacion(Activacion activacion) {
		this.activacion = activacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "estado", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Actestado getActestado() {
		return this.actestado;
	}

	public void setActestado(Actestado actestado) {
		this.actestado = actestado;
	}

	@Column(name = "observacion", length = 2000)
	@Length(max = 2000)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

}
