package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Franquicia generated by hbm2java
 */
@Entity
@Table(name = "franquicia")
public class Franquicia implements java.io.Serializable {

	private String codfranquicia;
	private String nombrefranquicia;
	private BigDecimal porcentaje;
	private Set<Tasadolarpromotorparametro> tasadolarpromotorparametros = new HashSet<Tasadolarpromotorparametro>(
			0);
	private Set<Porcentajecomisiontxparam> porcentajecomisiontxparams = new HashSet<Porcentajecomisiontxparam>(
			0);
	private Set<Tasaeuroparametro> tasaeuroparametros = new HashSet<Tasaeuroparametro>(
			0);
	private Set<Tasaeuropromotorparametro> tasaeuropromotorparametros = new HashSet<Tasaeuropromotorparametro>(
			0);
	private Set<Tasadolarparametro> tasadolarparametros = new HashSet<Tasadolarparametro>(
			0);
	private Set<Porcentcomisiontxparampromo> porcentcomisiontxparampromos = new HashSet<Porcentcomisiontxparampromo>(
			0);
	private Set<Tarjeta> tarjetas = new HashSet<Tarjeta>(0);
	private Set<Promotorfranquicia> promotorfranquicias = new HashSet<Promotorfranquicia>(
			0);

	public Franquicia() {
	}

	public Franquicia(String codfranquicia, String nombrefranquicia) {
		this.codfranquicia = codfranquicia;
		this.nombrefranquicia = nombrefranquicia;
	}

	public Franquicia(String codfranquicia, String nombrefranquicia,
			BigDecimal porcentaje,
			Set<Tasadolarpromotorparametro> tasadolarpromotorparametros,
			Set<Porcentajecomisiontxparam> porcentajecomisiontxparams,
			Set<Tasaeuroparametro> tasaeuroparametros,
			Set<Tasaeuropromotorparametro> tasaeuropromotorparametros,
			Set<Tasadolarparametro> tasadolarparametros,
			Set<Porcentcomisiontxparampromo> porcentcomisiontxparampromos,
			Set<Tarjeta> tarjetas, Set<Promotorfranquicia> promotorfranquicias) {
		this.codfranquicia = codfranquicia;
		this.nombrefranquicia = nombrefranquicia;
		this.porcentaje = porcentaje;
		this.tasadolarpromotorparametros = tasadolarpromotorparametros;
		this.porcentajecomisiontxparams = porcentajecomisiontxparams;
		this.tasaeuroparametros = tasaeuroparametros;
		this.tasaeuropromotorparametros = tasaeuropromotorparametros;
		this.tasadolarparametros = tasadolarparametros;
		this.porcentcomisiontxparampromos = porcentcomisiontxparampromos;
		this.tarjetas = tarjetas;
		this.promotorfranquicias = promotorfranquicias;
	}

	@Id
	@Column(name = "codfranquicia", unique = true, nullable = false, length = 1)
	@NotNull
	@Length(max = 1)
	public String getCodfranquicia() {
		return this.codfranquicia;
	}

	public void setCodfranquicia(String codfranquicia) {
		this.codfranquicia = codfranquicia;
	}

	@Column(name = "nombrefranquicia", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getNombrefranquicia() {
		return this.nombrefranquicia;
	}

	public void setNombrefranquicia(String nombrefranquicia) {
		this.nombrefranquicia = nombrefranquicia;
	}

	@Column(name = "porcentaje", precision = 5, scale = 3)
	public BigDecimal getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(BigDecimal porcentaje) {
		this.porcentaje = porcentaje;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "franquicia")
	public Set<Tasadolarpromotorparametro> getTasadolarpromotorparametros() {
		return this.tasadolarpromotorparametros;
	}

	public void setTasadolarpromotorparametros(
			Set<Tasadolarpromotorparametro> tasadolarpromotorparametros) {
		this.tasadolarpromotorparametros = tasadolarpromotorparametros;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "franquicia")
	public Set<Porcentajecomisiontxparam> getPorcentajecomisiontxparams() {
		return this.porcentajecomisiontxparams;
	}

	public void setPorcentajecomisiontxparams(
			Set<Porcentajecomisiontxparam> porcentajecomisiontxparams) {
		this.porcentajecomisiontxparams = porcentajecomisiontxparams;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "franquicia")
	public Set<Tasaeuroparametro> getTasaeuroparametros() {
		return this.tasaeuroparametros;
	}

	public void setTasaeuroparametros(Set<Tasaeuroparametro> tasaeuroparametros) {
		this.tasaeuroparametros = tasaeuroparametros;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "franquicia")
	public Set<Tasaeuropromotorparametro> getTasaeuropromotorparametros() {
		return this.tasaeuropromotorparametros;
	}

	public void setTasaeuropromotorparametros(
			Set<Tasaeuropromotorparametro> tasaeuropromotorparametros) {
		this.tasaeuropromotorparametros = tasaeuropromotorparametros;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "franquicia")
	public Set<Tasadolarparametro> getTasadolarparametros() {
		return this.tasadolarparametros;
	}

	public void setTasadolarparametros(
			Set<Tasadolarparametro> tasadolarparametros) {
		this.tasadolarparametros = tasadolarparametros;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "franquicia")
	public Set<Porcentcomisiontxparampromo> getPorcentcomisiontxparampromos() {
		return this.porcentcomisiontxparampromos;
	}

	public void setPorcentcomisiontxparampromos(
			Set<Porcentcomisiontxparampromo> porcentcomisiontxparampromos) {
		this.porcentcomisiontxparampromos = porcentcomisiontxparampromos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "franquicia")
	public Set<Tarjeta> getTarjetas() {
		return this.tarjetas;
	}

	public void setTarjetas(Set<Tarjeta> tarjetas) {
		this.tarjetas = tarjetas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "franquicia")
	public Set<Promotorfranquicia> getPromotorfranquicias() {
		return this.promotorfranquicias;
	}

	public void setPromotorfranquicias(
			Set<Promotorfranquicia> promotorfranquicias) {
		this.promotorfranquicias = promotorfranquicias;
	}

}
