package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * Franquiciaestablecimiento generated by hbm2java
 */
@Entity
@Table(name = "franquiciaestablecimiento")
public class Franquiciaestablecimiento implements java.io.Serializable {

	private FranquiciaestablecimientoId id;
	private BigDecimal porcentaje;

	public Franquiciaestablecimiento() {
	}

	public Franquiciaestablecimiento(FranquiciaestablecimientoId id) {
		this.id = id;
	}

	public Franquiciaestablecimiento(FranquiciaestablecimientoId id,
			BigDecimal porcentaje) {
		this.id = id;
		this.porcentaje = porcentaje;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "establecimiento", column = @Column(name = "establecimiento", nullable = false, length = 8)),
			@AttributeOverride(name = "franquicia", column = @Column(name = "franquicia", nullable = false, length = 1)) })
	@NotNull
	public FranquiciaestablecimientoId getId() {
		return this.id;
	}

	public void setId(FranquiciaestablecimientoId id) {
		this.id = id;
	}

	@Column(name = "porcentaje", precision = 3)
	public BigDecimal getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(BigDecimal porcentaje) {
		this.porcentaje = porcentaje;
	}

}
