package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * Gravamenestablecimiento generated by hbm2java
 */
@Entity
@Table(name = "gravamenestablecimiento")
public class Gravamenestablecimiento implements java.io.Serializable {

	private GravamenestablecimientoId id;
	private Establecimiento establecimiento;
	private Gravamen gravamen;
	private BigDecimal porcentaje;
	private Boolean iva;
	private Boolean activo;

	public Gravamenestablecimiento() {
	}

	public Gravamenestablecimiento(GravamenestablecimientoId id,
			Establecimiento establecimiento, Gravamen gravamen) {
		this.id = id;
		this.establecimiento = establecimiento;
		this.gravamen = gravamen;
	}

	public Gravamenestablecimiento(GravamenestablecimientoId id,
			Establecimiento establecimiento, Gravamen gravamen,
			BigDecimal porcentaje, Boolean iva, Boolean activo) {
		this.id = id;
		this.establecimiento = establecimiento;
		this.gravamen = gravamen;
		this.porcentaje = porcentaje;
		this.iva = iva;
		this.activo = activo;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "codigounico", column = @Column(name = "codigounico", nullable = false, length = 8)),
			@AttributeOverride(name = "gravamen", column = @Column(name = "gravamen", nullable = false, length = 2)) })
	@NotNull
	public GravamenestablecimientoId getId() {
		return this.id;
	}

	public void setId(GravamenestablecimientoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigounico", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Establecimiento getEstablecimiento() {
		return this.establecimiento;
	}

	public void setEstablecimiento(Establecimiento establecimiento) {
		this.establecimiento = establecimiento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "gravamen", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Gravamen getGravamen() {
		return this.gravamen;
	}

	public void setGravamen(Gravamen gravamen) {
		this.gravamen = gravamen;
	}

	@Column(name = "porcentaje", precision = 5, scale = 3)
	public BigDecimal getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(BigDecimal porcentaje) {
		this.porcentaje = porcentaje;
	}

	@Column(name = "iva")
	public Boolean getIva() {
		return this.iva;
	}

	public void setIva(Boolean iva) {
		this.iva = iva;
	}

	@Column(name = "activo")
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

}
