package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * InventarioId generated by hbm2java
 */
@Embeddable
public class InventarioId implements java.io.Serializable {

	private String refproducto;
	private String codigounico;

	public InventarioId() {
	}

	public InventarioId(String refproducto, String codigounico) {
		this.refproducto = refproducto;
		this.codigounico = codigounico;
	}

	@Column(name = "refproducto", unique = true, nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getRefproducto() {
		return this.refproducto;
	}

	public void setRefproducto(String refproducto) {
		this.refproducto = refproducto;
	}

	@Column(name = "codigounico", nullable = false, length = 8)
	@NotNull
	@Length(max = 8)
	public String getCodigounico() {
		return this.codigounico;
	}

	public void setCodigounico(String codigounico) {
		this.codigounico = codigounico;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InventarioId))
			return false;
		InventarioId castOther = (InventarioId) other;

		return ((this.getRefproducto() == castOther.getRefproducto()) || (this
				.getRefproducto() != null
				&& castOther.getRefproducto() != null && this.getRefproducto()
				.equals(castOther.getRefproducto())))
				&& ((this.getCodigounico() == castOther.getCodigounico()) || (this
						.getCodigounico() != null
						&& castOther.getCodigounico() != null && this
						.getCodigounico().equals(castOther.getCodigounico())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getRefproducto() == null ? 0 : this.getRefproducto()
						.hashCode());
		result = 37
				* result
				+ (getCodigounico() == null ? 0 : this.getCodigounico()
						.hashCode());
		return result;
	}

}
