package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Operacion generated by hbm2java
 */
@Entity
@Table(name = "operacion")
public class Operacion implements java.io.Serializable {

	private int codoperacion;
	private String descripcion;

	public Operacion() {
	}

	public Operacion(int codoperacion) {
		this.codoperacion = codoperacion;
	}

	public Operacion(int codoperacion, String descripcion) {
		this.codoperacion = codoperacion;
		this.descripcion = descripcion;
	}

	@Id
	@Column(name = "codoperacion", unique = true, nullable = false)
	public int getCodoperacion() {
		return this.codoperacion;
	}

	public void setCodoperacion(int codoperacion) {
		this.codoperacion = codoperacion;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
