package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Paisiso generated by hbm2java
 */
@Entity
@Table(name = "paisiso")
public class Paisiso implements java.io.Serializable {

	private String codigopais;
	private String nombrepaisEs;
	private String nombrepaisEn;
	private String capital;
	private String nombrecompletoEn;
	private String codigopaisNumero;
	private String codigo31663Es;
	private String codigomoneda;
	private String nombreMoneda;
	private String pathBanderaRelativo;
	private String pathBanderaAbsoluta;
	private Boolean estado;
	private String pathBanderasExtracto;
	private String pathBanderaGui;
	private Set<Tasabolivartransferpais> tasabolivartransferpaises = new HashSet<Tasabolivartransferpais>(
			0);
	private Set<Pais> paises = new HashSet<Pais>(0);

	public Paisiso() {
	}

	public Paisiso(String codigopais) {
		this.codigopais = codigopais;
	}

	public Paisiso(String codigopais, String nombrepaisEs, String nombrepaisEn,
			String capital, String nombrecompletoEn, String codigopaisNumero,
			String codigo31663Es, String codigomoneda, String nombreMoneda,
			String pathBanderaRelativo, String pathBanderaAbsoluta,
			Boolean estado, String pathBanderasExtracto,
			Set<Tasabolivartransferpais> tasabolivartransferpaises,
			Set<Pais> paises) {
		this.codigopais = codigopais;
		this.nombrepaisEs = nombrepaisEs;
		this.nombrepaisEn = nombrepaisEn;
		this.capital = capital;
		this.nombrecompletoEn = nombrecompletoEn;
		this.codigopaisNumero = codigopaisNumero;
		this.codigo31663Es = codigo31663Es;
		this.codigomoneda = codigomoneda;
		this.nombreMoneda = nombreMoneda;
		this.pathBanderaRelativo = pathBanderaRelativo;
		this.pathBanderaAbsoluta = pathBanderaAbsoluta;
		this.estado = estado;
		this.pathBanderasExtracto = pathBanderasExtracto;
		this.tasabolivartransferpaises = tasabolivartransferpaises;
		this.paises = paises;
	}

	@Id
	@Column(name = "codigopais", unique = true, nullable = false, length = 5)
	@NotNull
	@Length(max = 5)
	public String getCodigopais() {
		return this.codigopais;
	}

	public void setCodigopais(String codigopais) {
		this.codigopais = codigopais;
	}

	@Column(name = "nombrepais_es", length = 200)
	@Length(max = 200)
	public String getNombrepaisEs() {
		return this.nombrepaisEs;
	}

	public void setNombrepaisEs(String nombrepaisEs) {
		this.nombrepaisEs = nombrepaisEs;
	}

	@Column(name = "nombrepais_en", length = 200)
	@Length(max = 200)
	public String getNombrepaisEn() {
		return this.nombrepaisEn;
	}

	public void setNombrepaisEn(String nombrepaisEn) {
		this.nombrepaisEn = nombrepaisEn;
	}

	@Column(name = "capital", length = 200)
	@Length(max = 200)
	public String getCapital() {
		return this.capital;
	}

	public void setCapital(String capital) {
		this.capital = capital;
	}

	@Column(name = "nombrecompleto_en", length = 200)
	@Length(max = 200)
	public String getNombrecompletoEn() {
		return this.nombrecompletoEn;
	}

	public void setNombrecompletoEn(String nombrecompletoEn) {
		this.nombrecompletoEn = nombrecompletoEn;
	}

	@Column(name = "codigopais_numero", length = 4)
	@Length(max = 4)
	public String getCodigopaisNumero() {
		return this.codigopaisNumero;
	}

	public void setCodigopaisNumero(String codigopaisNumero) {
		this.codigopaisNumero = codigopaisNumero;
	}

	@Column(name = "codigo3166_3_es", length = 5)
	@Length(max = 5)
	public String getCodigo31663Es() {
		return this.codigo31663Es;
	}

	public void setCodigo31663Es(String codigo31663Es) {
		this.codigo31663Es = codigo31663Es;
	}

	@Column(name = "codigomoneda", length = 5)
	@Length(max = 5)
	public String getCodigomoneda() {
		return this.codigomoneda;
	}

	public void setCodigomoneda(String codigomoneda) {
		this.codigomoneda = codigomoneda;
	}

	@Column(name = "nombre_moneda", length = 60)
	@Length(max = 60)
	public String getNombreMoneda() {
		return this.nombreMoneda;
	}

	public void setNombreMoneda(String nombreMoneda) {
		this.nombreMoneda = nombreMoneda;
	}

	@Column(name = "path_bandera_relativo", length = 60)
	@Length(max = 60)
	public String getPathBanderaRelativo() {
		return this.pathBanderaRelativo;
	}

	public void setPathBanderaRelativo(String pathBanderaRelativo) {
		this.pathBanderaRelativo = pathBanderaRelativo;
	}

	@Column(name = "path_bandera_absoluta", length = 60)
	@Length(max = 60)
	public String getPathBanderaAbsoluta() {
		return this.pathBanderaAbsoluta;
	}

	public void setPathBanderaAbsoluta(String pathBanderaAbsoluta) {
		this.pathBanderaAbsoluta = pathBanderaAbsoluta;
	}

	@Column(name = "estado", precision = 1, scale = 0)
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	@Column(name = "path_banderas_extracto", length = 70)
	@Length(max = 70)
	public String getPathBanderasExtracto() {
		return this.pathBanderasExtracto;
	}

	public void setPathBanderasExtracto(String pathBanderasExtracto) {
		this.pathBanderasExtracto = pathBanderasExtracto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paisiso")
	public Set<Tasabolivartransferpais> getTasabolivartransferpaises() {
		return this.tasabolivartransferpaises;
	}

	public void setTasabolivartransferpaises(
			Set<Tasabolivartransferpais> tasabolivartransferpaises) {
		this.tasabolivartransferpaises = tasabolivartransferpaises;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paisiso")
	public Set<Pais> getPaises() {
		return this.paises;
	}

	public void setPaises(Set<Pais> paises) {
		this.paises = paises;
	}

	@Column(name = "path_bandera_gui", length = 60)
	@Length(max = 60)
	public String getPathBanderaGui() {
		return pathBanderaGui;
	}

	public void setPathBanderaGui(String pathBanderaGui) {
		this.pathBanderaGui = pathBanderaGui;
	}
	
	

}
