package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Proxy;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Pais generated by hbm2java
 */
@Entity

@Table(name = "pais")
public class Pais implements java.io.Serializable {

	private String codigopais;
	private Paisiso paisiso;
	private String nombre;
	private Boolean estado;
	private Set<Tasaeuroparametro> tasaeuroparametros = new HashSet<Tasaeuroparametro>(
			0);
	private Set<Promotorcomisiontx> promotorcomisiontxes = new HashSet<Promotorcomisiontx>(
			0);
	private Set<Promotortasa> promotortasas = new HashSet<Promotortasa>(0);
	private Set<Tasaeuropromotorparametro> tasaeuropromotorparametros = new HashSet<Tasaeuropromotorparametro>(
			0);
	private Set<Porcentajecomisiontx> porcentajecomisiontxes = new HashSet<Porcentajecomisiontx>(
			0);
	private Set<Porcentcomisiontxparampromo> porcentcomisiontxparampromos = new HashSet<Porcentcomisiontxparampromo>(
			0);
	private Set<Tasadolarparametro> tasadolarparametros = new HashSet<Tasadolarparametro>(
			0);
	private Set<Establecimiento> establecimientos = new HashSet<Establecimiento>(
			0);
	private Set<Tasadolarpromotorparametro> tasadolarpromotorparametros = new HashSet<Tasadolarpromotorparametro>(
			0);
	private Set<Porcentajecomisiontxparam> porcentajecomisiontxparams = new HashSet<Porcentajecomisiontxparam>(
			0);
	private Set<Tasadolar> tasadolars = new HashSet<Tasadolar>(0);

	public Pais() {
	}

	public Pais(String codigopais) {
		this.codigopais = codigopais;
	}

	public Pais(String codigopais, Paisiso paisiso, String nombre,
			Boolean estado, Set<Tasaeuroparametro> tasaeuroparametros,
			Set<Promotorcomisiontx> promotorcomisiontxes,
			Set<Promotortasa> promotortasas,
			Set<Tasaeuropromotorparametro> tasaeuropromotorparametros,
			Set<Porcentajecomisiontx> porcentajecomisiontxes,
			Set<Porcentcomisiontxparampromo> porcentcomisiontxparampromos,
			Set<Tasadolarparametro> tasadolarparametros,
			Set<Establecimiento> establecimientos,
			Set<Tasadolarpromotorparametro> tasadolarpromotorparametros,
			Set<Porcentajecomisiontxparam> porcentajecomisiontxparams,
			Set<Tasadolar> tasadolars) {
		this.codigopais = codigopais;
		this.paisiso = paisiso;
		this.nombre = nombre;
		this.estado = estado;
		this.tasaeuroparametros = tasaeuroparametros;
		this.promotorcomisiontxes = promotorcomisiontxes;
		this.promotortasas = promotortasas;
		this.tasaeuropromotorparametros = tasaeuropromotorparametros;
		this.porcentajecomisiontxes = porcentajecomisiontxes;
		this.porcentcomisiontxparampromos = porcentcomisiontxparampromos;
		this.tasadolarparametros = tasadolarparametros;
		this.establecimientos = establecimientos;
		this.tasadolarpromotorparametros = tasadolarpromotorparametros;
		this.porcentajecomisiontxparams = porcentajecomisiontxparams;
		this.tasadolars = tasadolars;
	}

	@Id
	@Column(name = "codigopais", unique = true, nullable = false, length = 5)
	@NotNull
	@Length(max = 5)
	public String getCodigopais() {
		return this.codigopais;
	}

	public void setCodigopais(String codigopais) {
		this.codigopais = codigopais;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigopaisiso")
	public Paisiso getPaisiso() {
		return this.paisiso;
	}

	public void setPaisiso(Paisiso paisiso) {
		this.paisiso = paisiso;
	}

	@Column(name = "nombre", length = 25)
	@Length(max = 25)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "estado", precision = 1, scale = 0)
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<Tasaeuroparametro> getTasaeuroparametros() {
		return this.tasaeuroparametros;
	}

	public void setTasaeuroparametros(Set<Tasaeuroparametro> tasaeuroparametros) {
		this.tasaeuroparametros = tasaeuroparametros;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<Promotorcomisiontx> getPromotorcomisiontxes() {
		return this.promotorcomisiontxes;
	}

	public void setPromotorcomisiontxes(
			Set<Promotorcomisiontx> promotorcomisiontxes) {
		this.promotorcomisiontxes = promotorcomisiontxes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<Promotortasa> getPromotortasas() {
		return this.promotortasas;
	}

	public void setPromotortasas(Set<Promotortasa> promotortasas) {
		this.promotortasas = promotortasas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<Tasaeuropromotorparametro> getTasaeuropromotorparametros() {
		return this.tasaeuropromotorparametros;
	}

	public void setTasaeuropromotorparametros(
			Set<Tasaeuropromotorparametro> tasaeuropromotorparametros) {
		this.tasaeuropromotorparametros = tasaeuropromotorparametros;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<Porcentajecomisiontx> getPorcentajecomisiontxes() {
		return this.porcentajecomisiontxes;
	}

	public void setPorcentajecomisiontxes(
			Set<Porcentajecomisiontx> porcentajecomisiontxes) {
		this.porcentajecomisiontxes = porcentajecomisiontxes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<Porcentcomisiontxparampromo> getPorcentcomisiontxparampromos() {
		return this.porcentcomisiontxparampromos;
	}

	public void setPorcentcomisiontxparampromos(
			Set<Porcentcomisiontxparampromo> porcentcomisiontxparampromos) {
		this.porcentcomisiontxparampromos = porcentcomisiontxparampromos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<Tasadolarparametro> getTasadolarparametros() {
		return this.tasadolarparametros;
	}

	public void setTasadolarparametros(
			Set<Tasadolarparametro> tasadolarparametros) {
		this.tasadolarparametros = tasadolarparametros;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<Establecimiento> getEstablecimientos() {
		return this.establecimientos;
	}

	public void setEstablecimientos(Set<Establecimiento> establecimientos) {
		this.establecimientos = establecimientos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<Tasadolarpromotorparametro> getTasadolarpromotorparametros() {
		return this.tasadolarpromotorparametros;
	}

	public void setTasadolarpromotorparametros(
			Set<Tasadolarpromotorparametro> tasadolarpromotorparametros) {
		this.tasadolarpromotorparametros = tasadolarpromotorparametros;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<Porcentajecomisiontxparam> getPorcentajecomisiontxparams() {
		return this.porcentajecomisiontxparams;
	}

	public void setPorcentajecomisiontxparams(
			Set<Porcentajecomisiontxparam> porcentajecomisiontxparams) {
		this.porcentajecomisiontxparams = porcentajecomisiontxparams;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<Tasadolar> getTasadolars() {
		return this.tasadolars;
	}

	public void setTasadolars(Set<Tasadolar> tasadolars) {
		this.tasadolars = tasadolars;
	}

}
