package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.NotNull;

/**
 * Paridadmoneda generated by hbm2java
 */
@Entity
@Table(name = "paridadmoneda")
public class Paridadmoneda implements java.io.Serializable {

	private Date fecha;
	private Moneda monedaByCodmonedadestino;
	private Moneda monedaByCodmonedaorigen;
	private BigDecimal paridad;

	public Paridadmoneda() {
	}

	public Paridadmoneda(Date fecha) {
		this.fecha = fecha;
	}

	public Paridadmoneda(Date fecha, Moneda monedaByCodmonedadestino,
			Moneda monedaByCodmonedaorigen, BigDecimal paridad) {
		this.fecha = fecha;
		this.monedaByCodmonedadestino = monedaByCodmonedadestino;
		this.monedaByCodmonedaorigen = monedaByCodmonedaorigen;
		this.paridad = paridad;
	}

	@Id
	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", unique = true, nullable = false, length = 13)
	@NotNull
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codmonedadestino")
	public Moneda getMonedaByCodmonedadestino() {
		return this.monedaByCodmonedadestino;
	}

	public void setMonedaByCodmonedadestino(Moneda monedaByCodmonedadestino) {
		this.monedaByCodmonedadestino = monedaByCodmonedadestino;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codmonedaorigen")
	public Moneda getMonedaByCodmonedaorigen() {
		return this.monedaByCodmonedaorigen;
	}

	public void setMonedaByCodmonedaorigen(Moneda monedaByCodmonedaorigen) {
		this.monedaByCodmonedaorigen = monedaByCodmonedaorigen;
	}

	@Column(name = "paridad", precision = 2)
	public BigDecimal getParidad() {
		return this.paridad;
	}

	public void setParidad(BigDecimal paridad) {
		this.paridad = paridad;
	}

}
