package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * PersonaltipoprocesoId generated by hbm2java
 */
@Embeddable
public class PersonaltipoprocesoId implements java.io.Serializable {

	private String documento;
	private Date fechainicio;
	private String puntodeventa;
	private String tipoproceso;

	public PersonaltipoprocesoId() {
	}

	public PersonaltipoprocesoId(String documento, Date fechainicio,
			String puntodeventa, String tipoproceso) {
		this.documento = documento;
		this.fechainicio = fechainicio;
		this.puntodeventa = puntodeventa;
		this.tipoproceso = tipoproceso;
	}

	@Column(name = "documento", nullable = false, length = 15)
	@NotNull
	@Length(max = 15)
	public String getDocumento() {
		return this.documento;
	}

	public void setDocumento(String documento) {
		this.documento = documento;
	}

	@Column(name = "fechainicio", nullable = false, length = 29)
	@NotNull
	public Date getFechainicio() {
		return this.fechainicio;
	}

	public void setFechainicio(Date fechainicio) {
		this.fechainicio = fechainicio;
	}

	@Column(name = "puntodeventa", nullable = false, length = 1)
	@NotNull
	@Length(max = 1)
	public String getPuntodeventa() {
		return this.puntodeventa;
	}

	public void setPuntodeventa(String puntodeventa) {
		this.puntodeventa = puntodeventa;
	}

	@Column(name = "tipoproceso", nullable = false, length = 2)
	@NotNull
	@Length(max = 2)
	public String getTipoproceso() {
		return this.tipoproceso;
	}

	public void setTipoproceso(String tipoproceso) {
		this.tipoproceso = tipoproceso;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PersonaltipoprocesoId))
			return false;
		PersonaltipoprocesoId castOther = (PersonaltipoprocesoId) other;

		return ((this.getDocumento() == castOther.getDocumento()) || (this
				.getDocumento() != null
				&& castOther.getDocumento() != null && this.getDocumento()
				.equals(castOther.getDocumento())))
				&& ((this.getFechainicio() == castOther.getFechainicio()) || (this
						.getFechainicio() != null
						&& castOther.getFechainicio() != null && this
						.getFechainicio().equals(castOther.getFechainicio())))
				&& ((this.getPuntodeventa() == castOther.getPuntodeventa()) || (this
						.getPuntodeventa() != null
						&& castOther.getPuntodeventa() != null && this
						.getPuntodeventa().equals(castOther.getPuntodeventa())))
				&& ((this.getTipoproceso() == castOther.getTipoproceso()) || (this
						.getTipoproceso() != null
						&& castOther.getTipoproceso() != null && this
						.getTipoproceso().equals(castOther.getTipoproceso())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getDocumento() == null ? 0 : this.getDocumento().hashCode());
		result = 37
				* result
				+ (getFechainicio() == null ? 0 : this.getFechainicio()
						.hashCode());
		result = 37
				* result
				+ (getPuntodeventa() == null ? 0 : this.getPuntodeventa()
						.hashCode());
		result = 37
				* result
				+ (getTipoproceso() == null ? 0 : this.getTipoproceso()
						.hashCode());
		return result;
	}

}
