package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.NotNull;

/**
 * Personaltipoproceso generated by hbm2java
 */
@Entity
@Table(name = "personaltipoproceso")
public class Personaltipoproceso implements java.io.Serializable {

	private PersonaltipoprocesoId id;
	private Date fechafin;
	private BigDecimal porcentaje;

	public Personaltipoproceso() {
	}

	public Personaltipoproceso(PersonaltipoprocesoId id) {
		this.id = id;
	}

	public Personaltipoproceso(PersonaltipoprocesoId id, Date fechafin,
			BigDecimal porcentaje) {
		this.id = id;
		this.fechafin = fechafin;
		this.porcentaje = porcentaje;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "documento", column = @Column(name = "documento", nullable = false, length = 15)),
			@AttributeOverride(name = "fechainicio", column = @Column(name = "fechainicio", nullable = false, length = 29)),
			@AttributeOverride(name = "puntodeventa", column = @Column(name = "puntodeventa", nullable = false, length = 1)),
			@AttributeOverride(name = "tipoproceso", column = @Column(name = "tipoproceso", nullable = false, length = 2)) })
	@NotNull
	public PersonaltipoprocesoId getId() {
		return this.id;
	}

	public void setId(PersonaltipoprocesoId id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechafin", length = 13)
	public Date getFechafin() {
		return this.fechafin;
	}

	public void setFechafin(Date fechafin) {
		this.fechafin = fechafin;
	}

	@Column(name = "porcentaje", precision = 5, scale = 3)
	public BigDecimal getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(BigDecimal porcentaje) {
		this.porcentaje = porcentaje;
	}

}
