package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.NotNull;

/**
 * Porcentajecomisiontx generated by hbm2java
 */
@Entity
@Table(name = "porcentajecomisiontx")
public class Porcentajecomisiontx implements java.io.Serializable {

	private PorcentajecomisiontxId id;
	private Pais pais;
	private Date fechafin;
	private BigDecimal porcentaje;

	public Porcentajecomisiontx() {
	}

	public Porcentajecomisiontx(PorcentajecomisiontxId id, Pais pais) {
		this.id = id;
		this.pais = pais;
	}

	public Porcentajecomisiontx(PorcentajecomisiontxId id, Pais pais,
			Date fechafin, BigDecimal porcentaje) {
		this.id = id;
		this.pais = pais;
		this.fechafin = fechafin;
		this.porcentaje = porcentaje;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "codpais", column = @Column(name = "codpais", nullable = false, length = 5)),
			@AttributeOverride(name = "fechainicio", column = @Column(name = "fechainicio", nullable = false, length = 13)) })
	@NotNull
	public PorcentajecomisiontxId getId() {
		return this.id;
	}

	public void setId(PorcentajecomisiontxId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codpais", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechafin", length = 13)
	public Date getFechafin() {
		return this.fechafin;
	}

	public void setFechafin(Date fechafin) {
		this.fechafin = fechafin;
	}

	@Column(name = "porcentaje", precision = 4)
	public BigDecimal getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(BigDecimal porcentaje) {
		this.porcentaje = porcentaje;
	}

}
