package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name = "producto")
public class Producto implements java.io.Serializable {

	private String refproducto;
	private String nombreproducto;
	private String marca;
	private Integer valorminimo;
	private Integer valormaximo;
	private Short cantminimo;
	private Short cantmaximo;
	private Short porcentaje;
	private Set<Inventario> inventarios = new HashSet<Inventario>(0);

	public Producto() {
	}

	public Producto(String refproducto) {
		this.refproducto = refproducto;
	}

	public Producto(String refproducto, String nombreproducto, String marca,
			Integer valorminimo, Integer valormaximo, Short cantminimo,
			Short cantmaximo, Short porcentaje, Set<Inventario> inventarios) {
		this.refproducto = refproducto;
		this.nombreproducto = nombreproducto;
		this.marca = marca;
		this.valorminimo = valorminimo;
		this.valormaximo = valormaximo;
		this.cantminimo = cantminimo;
		this.cantmaximo = cantmaximo;
		this.porcentaje = porcentaje;
		this.inventarios = inventarios;
	}

	@Id
	@Column(name = "refproducto", unique = true, nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getRefproducto() {
		return this.refproducto;
	}

	public void setRefproducto(String refproducto) {
		this.refproducto = refproducto;
	}

	@Column(name = "nombreproducto", length = 50)
	@Length(max = 50)
	public String getNombreproducto() {
		return this.nombreproducto;
	}

	public void setNombreproducto(String nombreproducto) {
		this.nombreproducto = nombreproducto;
	}

	@Column(name = "marca", length = 20)
	@Length(max = 20)
	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	@Column(name = "valorminimo", precision = 8, scale = 0)
	public Integer getValorminimo() {
		return this.valorminimo;
	}

	public void setValorminimo(Integer valorminimo) {
		this.valorminimo = valorminimo;
	}

	@Column(name = "valormaximo", precision = 8, scale = 0)
	public Integer getValormaximo() {
		return this.valormaximo;
	}

	public void setValormaximo(Integer valormaximo) {
		this.valormaximo = valormaximo;
	}

	@Column(name = "cantminimo", precision = 3, scale = 0)
	public Short getCantminimo() {
		return this.cantminimo;
	}

	public void setCantminimo(Short cantminimo) {
		this.cantminimo = cantminimo;
	}

	@Column(name = "cantmaximo", precision = 3, scale = 0)
	public Short getCantmaximo() {
		return this.cantmaximo;
	}

	public void setCantmaximo(Short cantmaximo) {
		this.cantmaximo = cantmaximo;
	}

	@Column(name = "porcentaje")
	public Short getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(Short porcentaje) {
		this.porcentaje = porcentaje;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "producto")
	public Set<Inventario> getInventarios() {
		return this.inventarios;
	}

	public void setInventarios(Set<Inventario> inventarios) {
		this.inventarios = inventarios;
	}

}
