package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * PromotorcomisiontxId generated by hbm2java
 */
@Embeddable
public class PromotorcomisiontxId implements java.io.Serializable {

	private String codpais;
	private Date fechainicio;
	private String documento;

	public PromotorcomisiontxId() {
	}

	public PromotorcomisiontxId(String codpais, Date fechainicio,
			String documento) {
		this.codpais = codpais;
		this.fechainicio = fechainicio;
		this.documento = documento;
	}

	@Column(name = "codpais", nullable = false, length = 5)
	@NotNull
	@Length(max = 5)
	public String getCodpais() {
		return this.codpais;
	}

	public void setCodpais(String codpais) {
		this.codpais = codpais;
	}

	@Column(name = "fechainicio", nullable = false, length = 13)
	@NotNull
	public Date getFechainicio() {
		return this.fechainicio;
	}

	public void setFechainicio(Date fechainicio) {
		this.fechainicio = fechainicio;
	}

	@Column(name = "documento", nullable = false, length = 15)
	@NotNull
	@Length(max = 15)
	public String getDocumento() {
		return this.documento;
	}

	public void setDocumento(String documento) {
		this.documento = documento;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PromotorcomisiontxId))
			return false;
		PromotorcomisiontxId castOther = (PromotorcomisiontxId) other;

		return ((this.getCodpais() == castOther.getCodpais()) || (this
				.getCodpais() != null
				&& castOther.getCodpais() != null && this.getCodpais().equals(
				castOther.getCodpais())))
				&& ((this.getFechainicio() == castOther.getFechainicio()) || (this
						.getFechainicio() != null
						&& castOther.getFechainicio() != null && this
						.getFechainicio().equals(castOther.getFechainicio())))
				&& ((this.getDocumento() == castOther.getDocumento()) || (this
						.getDocumento() != null
						&& castOther.getDocumento() != null && this
						.getDocumento().equals(castOther.getDocumento())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodpais() == null ? 0 : this.getCodpais().hashCode());
		result = 37
				* result
				+ (getFechainicio() == null ? 0 : this.getFechainicio()
						.hashCode());
		result = 37 * result
				+ (getDocumento() == null ? 0 : this.getDocumento().hashCode());
		return result;
	}

}
