package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * Promotorfranquicia generated by hbm2java
 */
@Entity
@Table(name = "promotorfranquicia")
public class Promotorfranquicia implements java.io.Serializable {

	private PromotorfranquiciaId id;
	private Promotor promotor;
	private Franquicia franquicia;
	private BigDecimal porcentaje;

	public Promotorfranquicia() {
	}

	public Promotorfranquicia(PromotorfranquiciaId id, Promotor promotor,
			Franquicia franquicia) {
		this.id = id;
		this.promotor = promotor;
		this.franquicia = franquicia;
	}

	public Promotorfranquicia(PromotorfranquiciaId id, Promotor promotor,
			Franquicia franquicia, BigDecimal porcentaje) {
		this.id = id;
		this.promotor = promotor;
		this.franquicia = franquicia;
		this.porcentaje = porcentaje;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "codfranquicia", column = @Column(name = "codfranquicia", nullable = false, length = 1)),
			@AttributeOverride(name = "documento", column = @Column(name = "documento", nullable = false, length = 15)) })
	@NotNull
	public PromotorfranquiciaId getId() {
		return this.id;
	}

	public void setId(PromotorfranquiciaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "documento", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Promotor getPromotor() {
		return this.promotor;
	}

	public void setPromotor(Promotor promotor) {
		this.promotor = promotor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codfranquicia", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Franquicia getFranquicia() {
		return this.franquicia;
	}

	public void setFranquicia(Franquicia franquicia) {
		this.franquicia = franquicia;
	}

	@Column(name = "porcentaje", precision = 5, scale = 3)
	public BigDecimal getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(BigDecimal porcentaje) {
		this.porcentaje = porcentaje;
	}

}
