package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * PromotortasaId generated by hbm2java
 */
@Embeddable
public class PromotortasaId implements java.io.Serializable {

	private String documento;
	private String codigopais;
	private Date fecha;

	public PromotortasaId() {
	}

	public PromotortasaId(String documento, String codigopais, Date fecha) {
		this.documento = documento;
		this.codigopais = codigopais;
		this.fecha = fecha;
	}

	@Column(name = "documento", nullable = false, length = 15)
	@NotNull
	@Length(max = 15)
	public String getDocumento() {
		return this.documento;
	}

	public void setDocumento(String documento) {
		this.documento = documento;
	}

	@Column(name = "codigopais", nullable = false, length = 5)
	@NotNull
	@Length(max = 5)
	public String getCodigopais() {
		return this.codigopais;
	}

	public void setCodigopais(String codigopais) {
		this.codigopais = codigopais;
	}

	@Column(name = "fecha", nullable = false, length = 13)
	@NotNull
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PromotortasaId))
			return false;
		PromotortasaId castOther = (PromotortasaId) other;

		return ((this.getDocumento() == castOther.getDocumento()) || (this
				.getDocumento() != null
				&& castOther.getDocumento() != null && this.getDocumento()
				.equals(castOther.getDocumento())))
				&& ((this.getCodigopais() == castOther.getCodigopais()) || (this
						.getCodigopais() != null
						&& castOther.getCodigopais() != null && this
						.getCodigopais().equals(castOther.getCodigopais())))
				&& ((this.getFecha() == castOther.getFecha()) || (this
						.getFecha() != null
						&& castOther.getFecha() != null && this.getFecha()
						.equals(castOther.getFecha())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getDocumento() == null ? 0 : this.getDocumento().hashCode());
		result = 37
				* result
				+ (getCodigopais() == null ? 0 : this.getCodigopais()
						.hashCode());
		result = 37 * result
				+ (getFecha() == null ? 0 : this.getFecha().hashCode());
		return result;
	}

}
