package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.NotNull;

/**
 * Puntoestablecimiento generated by hbm2java
 */
@Entity
@Table(name = "puntoestablecimiento")
public class Puntoestablecimiento implements java.io.Serializable {

	private PuntoestablecimientoId id;
	private Puntodeventa puntodeventa;
	private Establecimiento establecimiento;
	private Date fechafin;

	public Puntoestablecimiento() {
	}

	public Puntoestablecimiento(PuntoestablecimientoId id,
			Puntodeventa puntodeventa, Establecimiento establecimiento) {
		this.id = id;
		this.puntodeventa = puntodeventa;
		this.establecimiento = establecimiento;
	}

	public Puntoestablecimiento(PuntoestablecimientoId id,
			Puntodeventa puntodeventa, Establecimiento establecimiento,
			Date fechafin) {
		this.id = id;
		this.puntodeventa = puntodeventa;
		this.establecimiento = establecimiento;
		this.fechafin = fechafin;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "codigounico", column = @Column(name = "codigounico", nullable = false, length = 8)),
			@AttributeOverride(name = "codpuntoventa", column = @Column(name = "codpuntoventa", nullable = false, length = 1)),
			@AttributeOverride(name = "fechainicio", column = @Column(name = "fechainicio", nullable = false, length = 29)) })
	@NotNull
	public PuntoestablecimientoId getId() {
		return this.id;
	}

	public void setId(PuntoestablecimientoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codpuntoventa", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Puntodeventa getPuntodeventa() {
		return this.puntodeventa;
	}

	public void setPuntodeventa(Puntodeventa puntodeventa) {
		this.puntodeventa = puntodeventa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigounico", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Establecimiento getEstablecimiento() {
		return this.establecimiento;
	}

	public void setEstablecimiento(Establecimiento establecimiento) {
		this.establecimiento = establecimiento;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechafin", length = 29)
	public Date getFechafin() {
		return this.fechafin;
	}

	public void setFechafin(Date fechafin) {
		this.fechafin = fechafin;
	}

}
