package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Puntodeventa generated by hbm2java
 */
@Entity
@Table(name = "puntodeventa")
public class Puntodeventa implements java.io.Serializable {

	private String codpuntoventa;
	private String nombre;
	private Set<Puntoestablecimiento> puntoestablecimientos = new HashSet<Puntoestablecimiento>(
			0);

	public Puntodeventa() {
	}

	public Puntodeventa(String codpuntoventa) {
		this.codpuntoventa = codpuntoventa;
	}

	public Puntodeventa(String codpuntoventa, String nombre,
			Set<Puntoestablecimiento> puntoestablecimientos) {
		this.codpuntoventa = codpuntoventa;
		this.nombre = nombre;
		this.puntoestablecimientos = puntoestablecimientos;
	}

	@Id
	@Column(name = "codpuntoventa", unique = true, nullable = false, length = 1)
	@NotNull
	@Length(max = 1)
	public String getCodpuntoventa() {
		return this.codpuntoventa;
	}

	public void setCodpuntoventa(String codpuntoventa) {
		this.codpuntoventa = codpuntoventa;
	}

	@Column(name = "nombre", length = 50)
	@Length(max = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "puntodeventa")
	public Set<Puntoestablecimiento> getPuntoestablecimientos() {
		return this.puntoestablecimientos;
	}

	public void setPuntoestablecimientos(
			Set<Puntoestablecimiento> puntoestablecimientos) {
		this.puntoestablecimientos = puntoestablecimientos;
	}

}
