package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * PuntoestablecimientoId generated by hbm2java
 */
@Embeddable
public class PuntoestablecimientoId implements java.io.Serializable {

	private String codigounico;
	private String codpuntoventa;
	private Date fechainicio;

	public PuntoestablecimientoId() {
	}

	public PuntoestablecimientoId(String codigounico, String codpuntoventa,
			Date fechainicio) {
		this.codigounico = codigounico;
		this.codpuntoventa = codpuntoventa;
		this.fechainicio = fechainicio;
	}

	@Column(name = "codigounico", nullable = false, length = 8)
	@NotNull
	@Length(max = 8)
	public String getCodigounico() {
		return this.codigounico;
	}

	public void setCodigounico(String codigounico) {
		this.codigounico = codigounico;
	}

	@Column(name = "codpuntoventa", nullable = false, length = 1)
	@NotNull
	@Length(max = 1)
	public String getCodpuntoventa() {
		return this.codpuntoventa;
	}

	public void setCodpuntoventa(String codpuntoventa) {
		this.codpuntoventa = codpuntoventa;
	}

	@Column(name = "fechainicio", nullable = false, length = 29)
	@NotNull
	public Date getFechainicio() {
		return this.fechainicio;
	}

	public void setFechainicio(Date fechainicio) {
		this.fechainicio = fechainicio;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PuntoestablecimientoId))
			return false;
		PuntoestablecimientoId castOther = (PuntoestablecimientoId) other;

		return ((this.getCodigounico() == castOther.getCodigounico()) || (this
				.getCodigounico() != null
				&& castOther.getCodigounico() != null && this.getCodigounico()
				.equals(castOther.getCodigounico())))
				&& ((this.getCodpuntoventa() == castOther.getCodpuntoventa()) || (this
						.getCodpuntoventa() != null
						&& castOther.getCodpuntoventa() != null && this
						.getCodpuntoventa()
						.equals(castOther.getCodpuntoventa())))
				&& ((this.getFechainicio() == castOther.getFechainicio()) || (this
						.getFechainicio() != null
						&& castOther.getFechainicio() != null && this
						.getFechainicio().equals(castOther.getFechainicio())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCodigounico() == null ? 0 : this.getCodigounico()
						.hashCode());
		result = 37
				* result
				+ (getCodpuntoventa() == null ? 0 : this.getCodpuntoventa()
						.hashCode());
		result = 37
				* result
				+ (getFechainicio() == null ? 0 : this.getFechainicio()
						.hashCode());
		return result;
	}

}
