package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Reportes generated by hbm2java
 */
@Entity
@Table(name = "reportes")
public class Reportes implements java.io.Serializable {

	private String codreporte;
	private String nombrereporte;
	private Short parametros;
	private String descripcion;

	public Reportes() {
	}

	public Reportes(String codreporte) {
		this.codreporte = codreporte;
	}

	public Reportes(String codreporte, String nombrereporte, Short parametros,
			String descripcion) {
		this.codreporte = codreporte;
		this.nombrereporte = nombrereporte;
		this.parametros = parametros;
		this.descripcion = descripcion;
	}

	@Id
	@Column(name = "codreporte", unique = true, nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getCodreporte() {
		return this.codreporte;
	}

	public void setCodreporte(String codreporte) {
		this.codreporte = codreporte;
	}

	@Column(name = "nombrereporte", length = 30)
	@Length(max = 30)
	public String getNombrereporte() {
		return this.nombrereporte;
	}

	public void setNombrereporte(String nombrereporte) {
		this.nombrereporte = nombrereporte;
	}

	@Column(name = "parametros", precision = 3, scale = 0)
	public Short getParametros() {
		return this.parametros;
	}

	public void setParametros(Short parametros) {
		this.parametros = parametros;
	}

	@Column(name = "descripcion", length = 150)
	@Length(max = 150)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
