package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Saldo generated by hbm2java
 */
@Entity
@Table(name = "saldo")
public class Saldo implements java.io.Serializable {

	private SaldoId id;
	private Personal personal;
	private BigDecimal saldo;
	private String usuariomod;
	private Date fechamod;

	public Saldo() {
	}

	public Saldo(SaldoId id, Personal personal) {
		this.id = id;
		this.personal = personal;
	}

	public Saldo(SaldoId id, Personal personal, BigDecimal saldo,
			String usuariomod, Date fechamod) {
		this.id = id;
		this.personal = personal;
		this.saldo = saldo;
		this.usuariomod = usuariomod;
		this.fechamod = fechamod;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "documento", column = @Column(name = "documento", nullable = false, length = 15)),
			@AttributeOverride(name = "fecha", column = @Column(name = "fecha", nullable = false, length = 13)) })
	@NotNull
	public SaldoId getId() {
		return this.id;
	}

	public void setId(SaldoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "documento", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Personal getPersonal() {
		return this.personal;
	}

	public void setPersonal(Personal personal) {
		this.personal = personal;
	}

	@Column(name = "saldo", precision = 15)
	public BigDecimal getSaldo() {
		return this.saldo;
	}

	public void setSaldo(BigDecimal saldo) {
		this.saldo = saldo;
	}

	@Column(name = "usuariomod", length = 15)
	@Length(max = 15)
	public String getUsuariomod() {
		return this.usuariomod;
	}

	public void setUsuariomod(String usuariomod) {
		this.usuariomod = usuariomod;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechamod", length = 13)
	public Date getFechamod() {
		return this.fechamod;
	}

	public void setFechamod(Date fechamod) {
		this.fechamod = fechamod;
	}

}
