package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Saldodiariopromotor generated by hbm2java
 */
@Entity
@Table(name = "saldodiariopromotor")
public class Saldodiariopromotor implements java.io.Serializable {

	private SaldodiariopromotorId id;
	private Promotor promotor;
	private BigDecimal saldo;
	private Date fechamod;
	private String usuariomod;

	public Saldodiariopromotor() {
	}

	public Saldodiariopromotor(SaldodiariopromotorId id, Promotor promotor) {
		this.id = id;
		this.promotor = promotor;
	}

	public Saldodiariopromotor(SaldodiariopromotorId id, Promotor promotor,
			BigDecimal saldo, Date fechamod, String usuariomod) {
		this.id = id;
		this.promotor = promotor;
		this.saldo = saldo;
		this.fechamod = fechamod;
		this.usuariomod = usuariomod;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "documento", column = @Column(name = "documento", nullable = false, length = 15)),
			@AttributeOverride(name = "fecha", column = @Column(name = "fecha", nullable = false, length = 13)) })
	@NotNull
	public SaldodiariopromotorId getId() {
		return this.id;
	}

	public void setId(SaldodiariopromotorId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "documento", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Promotor getPromotor() {
		return this.promotor;
	}

	public void setPromotor(Promotor promotor) {
		this.promotor = promotor;
	}

	@Column(name = "saldo", precision = 15)
	public BigDecimal getSaldo() {
		return this.saldo;
	}

	public void setSaldo(BigDecimal saldo) {
		this.saldo = saldo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechamod", length = 13)
	public Date getFechamod() {
		return this.fechamod;
	}

	public void setFechamod(Date fechamod) {
		this.fechamod = fechamod;
	}

	@Column(name = "usuariomod", length = 15)
	@Length(max = 15)
	public String getUsuariomod() {
		return this.usuariomod;
	}

	public void setUsuariomod(String usuariomod) {
		this.usuariomod = usuariomod;
	}

}
