package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Saldodepositos generated by hbm2java
 */
@Entity
@Table(name = "saldodepositos")
public class Saldodepositos implements java.io.Serializable {

	private SaldodepositosId id;
	private Tarjeta tarjeta;
	private BigDecimal saldo;
	private String usuariomod;
	private Date fechamod;

	public Saldodepositos() {
	}

	public Saldodepositos(SaldodepositosId id, Tarjeta tarjeta) {
		this.id = id;
		this.tarjeta = tarjeta;
	}

	public Saldodepositos(SaldodepositosId id, Tarjeta tarjeta,
			BigDecimal saldo, String usuariomod, Date fechamod) {
		this.id = id;
		this.tarjeta = tarjeta;
		this.saldo = saldo;
		this.usuariomod = usuariomod;
		this.fechamod = fechamod;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "numerotarjeta", column = @Column(name = "numerotarjeta", nullable = false, length = 16)),
			@AttributeOverride(name = "fecha", column = @Column(name = "fecha", nullable = false, length = 13)) })
	@NotNull
	public SaldodepositosId getId() {
		return this.id;
	}

	public void setId(SaldodepositosId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "numerotarjeta", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Tarjeta getTarjeta() {
		return this.tarjeta;
	}

	public void setTarjeta(Tarjeta tarjeta) {
		this.tarjeta = tarjeta;
	}

	@Column(name = "saldo", precision = 15)
	public BigDecimal getSaldo() {
		return this.saldo;
	}

	public void setSaldo(BigDecimal saldo) {
		this.saldo = saldo;
	}

	@Column(name = "usuariomod", length = 15)
	@Length(max = 15)
	public String getUsuariomod() {
		return this.usuariomod;
	}

	public void setUsuariomod(String usuariomod) {
		this.usuariomod = usuariomod;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechamod", length = 13)
	public Date getFechamod() {
		return this.fechamod;
	}

	public void setFechamod(Date fechamod) {
		this.fechamod = fechamod;
	}

}
