package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;

/**
 * Solicitudtransferencia generated by hbm2java
 */
@Entity
@Table(name = "solicitudtransferencia")
public class Solicitudtransferencia implements java.io.Serializable {

	private int consecutivo;
	private Integer depositos;
	private String documento;
	private Date fecha;
	private Integer saldoanterior;
	private Integer valor;

	public Solicitudtransferencia() {
	}

	public Solicitudtransferencia(int consecutivo) {
		this.consecutivo = consecutivo;
	}

	public Solicitudtransferencia(int consecutivo, Integer depositos,
			String documento, Date fecha, Integer saldoanterior, Integer valor) {
		this.consecutivo = consecutivo;
		this.depositos = depositos;
		this.documento = documento;
		this.fecha = fecha;
		this.saldoanterior = saldoanterior;
		this.valor = valor;
	}

	@Id
	@Column(name = "consecutivo", unique = true, nullable = false)
	public int getConsecutivo() {
		return this.consecutivo;
	}

	public void setConsecutivo(int consecutivo) {
		this.consecutivo = consecutivo;
	}

	@Column(name = "depositos")
	public Integer getDepositos() {
		return this.depositos;
	}

	public void setDepositos(Integer depositos) {
		this.depositos = depositos;
	}

	@Column(name = "documento", length = 15)
	@Length(max = 15)
	public String getDocumento() {
		return this.documento;
	}

	public void setDocumento(String documento) {
		this.documento = documento;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", length = 29)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "saldoanterior")
	public Integer getSaldoanterior() {
		return this.saldoanterior;
	}

	public void setSaldoanterior(Integer saldoanterior) {
		this.saldoanterior = saldoanterior;
	}

	@Column(name = "valor")
	public Integer getValor() {
		return this.valor;
	}

	public void setValor(Integer valor) {
		this.valor = valor;
	}

}
