package org.domain.monedaliquidacion.entity;

// Generated 23/12/2011 07:58:00 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Tarjeta generated by hbm2java
 */
@Entity
@Table(name = "tarjeta", schema = "public")
public class Tarjeta implements java.io.Serializable {

	private String numerotarjeta;
	private Promotor promotor;
	private Franquicia franquicia;
	private Banco banco;
	private int limite;
	private Date fechainicio;
	private Date fechafin;
	private Date fechamod;
	private String fechavencimiento;
	private String codseguridad;
	private String tarjetahabiente;
	private String direcciontarjetahabiente;
	private String cedulatarjetahabiente;
	private String telefonotarjetahabiente;
	private String usuariomod;
	private Set<Transaccion> transaccions = new HashSet<Transaccion>(0);
	private Set<Depositostarjeta> depositostarjetas = new HashSet<Depositostarjeta>(
			0);
	private Set<Tarjetaviaje> tarjetaviajes = new HashSet<Tarjetaviaje>(0);
	private Set<Autovoz> autovozs = new HashSet<Autovoz>(0);
	private Set<Solicitudtarjeta> solicitudtarjetas = new HashSet<Solicitudtarjeta>(
			0);
	private Boolean tac;

	public Tarjeta() {
	}

	public Tarjeta(String numerotarjeta, Promotor promotor,
			Franquicia franquicia, Banco banco, int limite,
			String fechavencimiento, String codseguridad,
			String tarjetahabiente, String direcciontarjetahabiente,
			String cedulatarjetahabiente, String telefonotarjetahabiente,
			String usuariomod, Date fechamod) {
		this.numerotarjeta = numerotarjeta;
		this.promotor = promotor;
		this.franquicia = franquicia;
		this.banco = banco;
		this.limite = limite;
		this.fechavencimiento = fechavencimiento;
		this.codseguridad = codseguridad;
		this.tarjetahabiente = tarjetahabiente;
		this.direcciontarjetahabiente = direcciontarjetahabiente;
		this.cedulatarjetahabiente = cedulatarjetahabiente;
		this.telefonotarjetahabiente = telefonotarjetahabiente;
		this.usuariomod = usuariomod;
		this.fechamod = fechamod;
	}

	public Tarjeta(String numerotarjeta, Promotor promotor,
			Franquicia franquicia, Banco banco, int limite, Date fechainicio,
			Date fechafin, String fechavencimiento, String codseguridad,
			String tarjetahabiente, String direcciontarjetahabiente,
			String cedulatarjetahabiente, String telefonotarjetahabiente,
			Set<Transaccion> transaccions,
			Set<Depositostarjeta> depositostarjetas,
			Set<Tarjetaviaje> tarjetaviajes,
			Set<Autovoz> autovozs,
			String usuariomod, Date fechamod,
			Set<Solicitudtarjeta> solicitudtarjetas) {
		this.numerotarjeta = numerotarjeta;
		this.promotor = promotor;
		this.franquicia = franquicia;
		this.banco = banco;
		this.limite = limite;
		this.fechainicio = fechainicio;
		this.fechafin = fechafin;
		this.fechavencimiento = fechavencimiento;
		this.codseguridad = codseguridad;
		this.tarjetahabiente = tarjetahabiente;
		this.direcciontarjetahabiente = direcciontarjetahabiente;
		this.cedulatarjetahabiente = cedulatarjetahabiente;
		this.telefonotarjetahabiente = telefonotarjetahabiente;
		this.transaccions = transaccions;
		this.depositostarjetas = depositostarjetas;
		this.tarjetaviajes = tarjetaviajes;
		this.autovozs = autovozs;
		this.usuariomod = usuariomod;
		this.fechamod = fechamod;
		this.solicitudtarjetas = solicitudtarjetas;
		this.tac = tac;
	}

	@Id
	@Column(name = "numerotarjeta", unique = true, nullable = false, length = 16)
	@NotNull
	@Length(max = 16)
	public String getNumerotarjeta() {
		return this.numerotarjeta;
	}

	public void setNumerotarjeta(String numerotarjeta) {
		this.numerotarjeta = numerotarjeta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "documento", nullable = false)
	@NotNull
	public Promotor getPromotor() {
		return this.promotor;
	}

	public void setPromotor(Promotor promotor) {
		this.promotor = promotor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "franquicia", nullable = false)
	@NotNull
	public Franquicia getFranquicia() {
		return this.franquicia;
	}

	public void setFranquicia(Franquicia franquicia) {
		this.franquicia = franquicia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bancoemisor", nullable = false)
	@NotNull
	public Banco getBanco() {
		return this.banco;
	}

	public void setBanco(Banco banco) {
		this.banco = banco;
	}

	@Column(name = "limite", nullable = false, precision = 7, scale = 0)
	public int getLimite() {
		return this.limite;
	}

	public void setLimite(int limite) {
		this.limite = limite;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechainicio", length = 29)
	public Date getFechainicio() {
		return this.fechainicio;
	}

	public void setFechainicio(Date fechainicio) {
		this.fechainicio = fechainicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechafin", length = 29)
	public Date getFechafin() {
		return this.fechafin;
	}

	public void setFechafin(Date fechafin) {
		this.fechafin = fechafin;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechamod", length = 29)
	public Date getFechamod() {
		return this.fechamod;
	}

	public void setFechamod(Date fechamod) {
		this.fechamod = fechamod;
	}

	@Column(name = "fechavencimiento", nullable = false, length = 5)
	@NotNull
	@Length(max = 5)
	public String getFechavencimiento() {
		return this.fechavencimiento;
	}

	public void setFechavencimiento(String fechavencimiento) {
		this.fechavencimiento = fechavencimiento;
	}

	@Column(name = "codseguridad", nullable = false, length = 4)
	@NotNull
	@Length(max = 4)
	public String getCodseguridad() {
		return this.codseguridad;
	}

	public void setCodseguridad(String codseguridad) {
		this.codseguridad = codseguridad;
	}

	@Column(name = "tarjetahabiente", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getTarjetahabiente() {
		return this.tarjetahabiente;
	}

	public void setTarjetahabiente(String tarjetahabiente) {
		this.tarjetahabiente = tarjetahabiente;
	}

	@Column(name = "direcciontarjetahabiente", nullable = false, length = 150)
	@NotNull
	@Length(max = 300)
	public String getDirecciontarjetahabiente() {
		return this.direcciontarjetahabiente;
	}

	public void setDirecciontarjetahabiente(String direcciontarjetahabiente) {
		this.direcciontarjetahabiente = direcciontarjetahabiente;
	}

	@Column(name = "cedulatarjetahabiente", nullable = false, length = 15)
	@NotNull
	@Length(max = 15)
	public String getCedulatarjetahabiente() {
		return this.cedulatarjetahabiente;
	}

	public void setCedulatarjetahabiente(String cedulatarjetahabiente) {
		this.cedulatarjetahabiente = cedulatarjetahabiente;
	}

	@Column(name = "telefonotarjetahabiente", nullable = false, length = 15)
	@NotNull
	@Length(max = 15)
	public String getTelefonotarjetahabiente() {
		return this.telefonotarjetahabiente;
	}

	public void setTelefonotarjetahabiente(String telefonotarjetahabiente) {
		this.telefonotarjetahabiente = telefonotarjetahabiente;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tarjeta")
	public Set<Transaccion> getTransaccions() {
		return this.transaccions;
	}

	public void setTransaccions(Set<Transaccion> transaccions) {
		this.transaccions = transaccions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tarjeta")
	public Set<Depositostarjeta> getDepositostarjetas() {
		return this.depositostarjetas;
	}

	public void setDepositostarjetas(Set<Depositostarjeta> depositostarjetas) {
		this.depositostarjetas = depositostarjetas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tarjeta")
	public Set<Tarjetaviaje> getTarjetaviajes() {
		return this.tarjetaviajes;
	}

	public void setTarjetaviajes(Set<Tarjetaviaje> tarjetaviajes) {
		this.tarjetaviajes = tarjetaviajes;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tarjeta")
	public Set<Autovoz> getAutovozs() {
		return this.autovozs;
	}

	public void setAutovozs(Set<Autovoz> autovozs) {
		this.autovozs = autovozs;
	}
	
	@Column(name = "usuariomod", nullable = true, length = 20)
	@Length(max = 20)
	public String getUsuariomod() {
		return this.usuariomod;
	}

	public void setUsuariomod(String usuariomod) {
		this.usuariomod = usuariomod;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tarjeta")
	public Set<Solicitudtarjeta> getSolicitudtarjetas() {
		return this.solicitudtarjetas;
	}

	public void setSolicitudtarjetas(Set<Solicitudtarjeta> solicitudtarjetas) {
		this.solicitudtarjetas = solicitudtarjetas;
	}
	
	@Column(name = "tac")
	public Boolean getTac() {
		return tac;
	}

	public void setTac(Boolean tac) {
		this.tac = tac;
	}

}
