package org.domain.monedaliquidacion.entity;

// Generated 30/12/2011 03:58:33 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Tarjetaviaje generated by hbm2java
 */
@Entity
@Table(name = "tarjetaviaje")
public class Tarjetaviaje implements java.io.Serializable {

	private TarjetaviajeId id;
	private Viaje viaje;
	private Tarjeta tarjeta;
	private Boolean estado;

	public Tarjetaviaje() {
	}

	public Tarjetaviaje(TarjetaviajeId id, Viaje viaje, Tarjeta tarjeta) {
		this.id = id;
		this.viaje = viaje;
		this.tarjeta = tarjeta;
	}

	public Tarjetaviaje(TarjetaviajeId id, Viaje viaje, Tarjeta tarjeta,
			Boolean estado) {
		this.id = id;
		this.viaje = viaje;
		this.tarjeta = tarjeta;
		this.estado = estado;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "numerotarjeta", column = @Column(name = "numerotarjeta", nullable = false, length = 16)),
			@AttributeOverride(name = "consecutivoviaje", column = @Column(name = "consecutivoviaje", nullable = false)) })
	@NotNull
	public TarjetaviajeId getId() {
		return this.id;
	}

	public void setId(TarjetaviajeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "consecutivoviaje", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Viaje getViaje() {
		return this.viaje;
	}

	public void setViaje(Viaje viaje) {
		this.viaje = viaje;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "numerotarjeta", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Tarjeta getTarjeta() {
		return this.tarjeta;
	}

	public void setTarjeta(Tarjeta tarjeta) {
		this.tarjeta = tarjeta;
	}

	@Column(name = "estado", precision = 1, scale = 0)
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}
	
	private Date fechamod;
	private String usuariomod;
	
	
	
	@Column(name = "usuariomod", nullable = true, length = 20)
	@Length(max = 20)
	public String getUsuariomod() {
		return this.usuariomod;
	}

	public void setUsuariomod(String usuariomod) {
		this.usuariomod = usuariomod;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechamod", length = 29)
	public Date getFechamod() {
		return this.fechamod;
	}

	public void setFechamod(Date fechamod) {
		this.fechamod = fechamod;
	}

}
