package org.domain.monedaliquidacion.entity;

// Generated 2/03/2013 03:06:19 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * TarjetaviajeNew generated by hbm2java
 */
@Entity
@Table(name = "tarjetaviaje_new")
public class TarjetaviajeNew implements java.io.Serializable {

	private TarjetaviajeNewId id;
	private Boolean estado;

	public TarjetaviajeNew() {
	}

	public TarjetaviajeNew(TarjetaviajeNewId id) {
		this.id = id;
	}

	public TarjetaviajeNew(TarjetaviajeNewId id, Boolean estado) {
		this.id = id;
		this.estado = estado;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "numerotarjeta", column = @Column(name = "numerotarjeta", nullable = false, length = 16)),
			@AttributeOverride(name = "consecutivoviaje", column = @Column(name = "consecutivoviaje", nullable = false)) })
	@NotNull
	public TarjetaviajeNewId getId() {
		return this.id;
	}

	public void setId(TarjetaviajeNewId id) {
		this.id = id;
	}

	@Column(name = "estado", precision = 1, scale = 0)
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

}
