package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Tasadebolivaroficina generated by hbm2java
 */
@Entity
@Table(name = "tasadebolivaroficina")
public class Tasadebolivaroficina implements java.io.Serializable {

	private TasadebolivaroficinaId id;
	private BigDecimal preciobolivar;
	private String usuariomod;
	private Date fechamod;

	public Tasadebolivaroficina() {
	}

	public Tasadebolivaroficina(TasadebolivaroficinaId id) {
		this.id = id;
	}

	public Tasadebolivaroficina(TasadebolivaroficinaId id,
			BigDecimal preciobolivar, String usuariomod, Date fechamod) {
		this.id = id;
		this.preciobolivar = preciobolivar;
		this.usuariomod = usuariomod;
		this.fechamod = fechamod;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "fecha", column = @Column(name = "fecha", nullable = false, length = 29)),
			@AttributeOverride(name = "tipo", column = @Column(name = "tipo", nullable = false, length = 1)) })
	@NotNull
	public TasadebolivaroficinaId getId() {
		return this.id;
	}

	public void setId(TasadebolivaroficinaId id) {
		this.id = id;
	}

	@Column(name = "preciobolivar", precision = 8)
	public BigDecimal getPreciobolivar() {
		return this.preciobolivar;
	}

	public void setPreciobolivar(BigDecimal preciobolivar) {
		this.preciobolivar = preciobolivar;
	}

	@Column(name = "usuariomod", length = 15)
	@Length(max = 15)
	public String getUsuariomod() {
		return this.usuariomod;
	}

	public void setUsuariomod(String usuariomod) {
		this.usuariomod = usuariomod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechamod", length = 29)
	public Date getFechamod() {
		return this.fechamod;
	}

	public void setFechamod(Date fechamod) {
		this.fechamod = fechamod;
	}

}
