package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * TasabolivartransferpaisId generated by hbm2java
 */
@Embeddable
public class TasabolivartransferpaisId implements java.io.Serializable {

	private Date fecha;
	private String codigopais;

	public TasabolivartransferpaisId() {
	}

	public TasabolivartransferpaisId(Date fecha, String codigopais) {
		this.fecha = fecha;
		this.codigopais = codigopais;
	}

	@Column(name = "fecha", nullable = false, length = 22)
	@NotNull
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "codigopais", nullable = false, length = 5)
	@NotNull
	@Length(max = 5)
	public String getCodigopais() {
		return this.codigopais;
	}

	public void setCodigopais(String codigopais) {
		this.codigopais = codigopais;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TasabolivartransferpaisId))
			return false;
		TasabolivartransferpaisId castOther = (TasabolivartransferpaisId) other;

		return ((this.getFecha() == castOther.getFecha()) || (this.getFecha() != null
				&& castOther.getFecha() != null && this.getFecha().equals(
				castOther.getFecha())))
				&& ((this.getCodigopais() == castOther.getCodigopais()) || (this
						.getCodigopais() != null
						&& castOther.getCodigopais() != null && this
						.getCodigopais().equals(castOther.getCodigopais())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getFecha() == null ? 0 : this.getFecha().hashCode());
		result = 37
				* result
				+ (getCodigopais() == null ? 0 : this.getCodigopais()
						.hashCode());
		return result;
	}

}
