package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * Tasabolivartransferpais generated by hbm2java
 */
@Entity
@Table(name = "tasabolivartransferpais")
public class Tasabolivartransferpais implements java.io.Serializable {

	private TasabolivartransferpaisId id;
	private Paisiso paisiso;
	private BigDecimal preciobolivar;

	public Tasabolivartransferpais() {
	}

	public Tasabolivartransferpais(TasabolivartransferpaisId id, Paisiso paisiso) {
		this.id = id;
		this.paisiso = paisiso;
	}

	public Tasabolivartransferpais(TasabolivartransferpaisId id,
			Paisiso paisiso, BigDecimal preciobolivar) {
		this.id = id;
		this.paisiso = paisiso;
		this.preciobolivar = preciobolivar;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "fecha", column = @Column(name = "fecha", nullable = false, length = 22)),
			@AttributeOverride(name = "codigopais", column = @Column(name = "codigopais", nullable = false, length = 5)) })
	@NotNull
	public TasabolivartransferpaisId getId() {
		return this.id;
	}

	public void setId(TasabolivartransferpaisId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigopais", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Paisiso getPaisiso() {
		return this.paisiso;
	}

	public void setPaisiso(Paisiso paisiso) {
		this.paisiso = paisiso;
	}

	@Column(name = "preciobolivar", precision = 8)
	public BigDecimal getPreciobolivar() {
		return this.preciobolivar;
	}

	public void setPreciobolivar(BigDecimal preciobolivar) {
		this.preciobolivar = preciobolivar;
	}

}
