package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Tipoproceso generated by hbm2java
 */
@Entity
@Table(name = "tipoproceso")
public class Tipoproceso implements java.io.Serializable {

	private String tipo;
	private String descripcion;

	public Tipoproceso() {
	}

	public Tipoproceso(String tipo) {
		this.tipo = tipo;
	}

	public Tipoproceso(String tipo, String descripcion) {
		this.tipo = tipo;
		this.descripcion = descripcion;
	}

	@Id
	@Column(name = "tipo", unique = true, nullable = false, length = 2)
	@NotNull
	@Length(max = 2)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "descripcion", length = 50)
	@Length(max = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
