package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Tipogasto generated by hbm2java
 */
@Entity
@Table(name = "tipogasto")
public class Tipogasto implements java.io.Serializable {

	private String codtipogasto;
	private String descripcion;
	private String tipo;
	private Set<Gastos> gastoses = new HashSet<Gastos>(0);

	public Tipogasto() {
	}

	public Tipogasto(String codtipogasto) {
		this.codtipogasto = codtipogasto;
	}

	public Tipogasto(String codtipogasto, String descripcion, String tipo,
			Set<Gastos> gastoses) {
		this.codtipogasto = codtipogasto;
		this.descripcion = descripcion;
		this.tipo = tipo;
		this.gastoses = gastoses;
	}

	@Id
	@Column(name = "codtipogasto", unique = true, nullable = false, length = 2)
	@NotNull
	@Length(max = 2)
	public String getCodtipogasto() {
		return this.codtipogasto;
	}

	public void setCodtipogasto(String codtipogasto) {
		this.codtipogasto = codtipogasto;
	}

	@Column(name = "descripcion", length = 50)
	@Length(max = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "tipo", length = 1)
	@Length(max = 1)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipogasto")
	public Set<Gastos> getGastoses() {
		return this.gastoses;
	}

	public void setGastoses(Set<Gastos> gastoses) {
		this.gastoses = gastoses;
	}

}
