package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * Transaccionerror generated by hbm2java
 */
@Entity
@Table(name = "transaccionerror")
public class Transaccionerror implements java.io.Serializable {

	private TransaccionerrorId id;

	public Transaccionerror() {
	}

	public Transaccionerror(TransaccionerrorId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "numerotarjeta", column = @Column(name = "numerotarjeta", nullable = false, length = 16)),
			@AttributeOverride(name = "codigounico", column = @Column(name = "codigounico", nullable = false, length = 8)),
			@AttributeOverride(name = "fechatx", column = @Column(name = "fechatx", nullable = false, length = 29)),
			@AttributeOverride(name = "tipotx", column = @Column(name = "tipotx", length = 1)),
			@AttributeOverride(name = "numfactura", column = @Column(name = "numfactura", length = 10)),
			@AttributeOverride(name = "fechamod", column = @Column(name = "fechamod", length = 29)),
			@AttributeOverride(name = "usuariomod", column = @Column(name = "usuariomod", length = 15)),
			@AttributeOverride(name = "asesor", column = @Column(name = "asesor", length = 15)),
			@AttributeOverride(name = "promotor", column = @Column(name = "promotor", length = 15)),
			@AttributeOverride(name = "digitador", column = @Column(name = "digitador", length = 15)),
			@AttributeOverride(name = "error", column = @Column(name = "error")) })
	@NotNull
	public TransaccionerrorId getId() {
		return this.id;
	}

	public void setId(TransaccionerrorId id) {
		this.id = id;
	}

}
