package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario")
public class Usuario implements java.io.Serializable {

	private String usuario;
	private String nombre;
	private String clave;
	private Boolean activo;
	private Boolean administrador;
	private Set<Rol> rols = new HashSet<Rol>(0);

	public Usuario() {
	}

	public Usuario(String usuario) {
		this.usuario = usuario;
	}

	public Usuario(String usuario, String nombre, String clave, Boolean activo,
			Boolean administrador, Set<Rol> rols) {
		this.usuario = usuario;
		this.nombre = nombre;
		this.clave = clave;
		this.activo = activo;
		this.administrador = administrador;
		this.rols = rols;
	}

	@Id
	@Column(name = "usuario", unique = true, nullable = false, length = 15)
	@NotNull
	@Length(max = 15)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "nombre", length = 50)
	@Length(max = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "clave", length = 16)
	@Length(max = 16)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@Column(name = "activo")
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "administrador")
	public Boolean getAdministrador() {
		return this.administrador;
	}

	public void setAdministrador(Boolean administrador) {
		this.administrador = administrador;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "usuariorol", joinColumns = { @JoinColumn(name = "usuario", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "rol", nullable = false, updatable = false) })
	public Set<Rol> getRols() {
		return this.rols;
	}

	public void setRols(Set<Rol> rols) {
		this.rols = rols;
	}

}
