package org.domain.monedaliquidacion.entity;


// Generated 28/12/2011 08:51:02 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * UsuariorolId generated by hbm2java
 */
@Embeddable
public class UsuariorolId implements java.io.Serializable {

	private String usuario;
	private int rol;

	public UsuariorolId() {
	}

	public UsuariorolId(String usuario, int rol) {
		this.usuario = usuario;
		this.rol = rol;
	}

	@Column(name = "usuario", nullable = false, length = 15)
	@NotNull
	@Length(max = 15)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "rol", nullable = false)
	public int getRol() {
		return this.rol;
	}

	public void setRol(int rol) {
		this.rol = rol;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuariorolId))
			return false;
		UsuariorolId castOther = (UsuariorolId) other;

		return ((this.getUsuario() == castOther.getUsuario()) || (this
				.getUsuario() != null
				&& castOther.getUsuario() != null && this.getUsuario().equals(
				castOther.getUsuario())))
				&& (this.getRol() == castOther.getRol());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUsuario() == null ? 0 : this.getUsuario().hashCode());
		result = 37 * result + this.getRol();
		return result;
	}

}
