package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Variable generated by hbm2java
 */
@Entity
@Table(name = "variable")
public class Variable implements java.io.Serializable {

	private int numregistro;
	private BigDecimal preciodolarven;
	private Date fechaini;
	private Date fechafin;

	public Variable() {
	}

	public Variable(int numregistro) {
		this.numregistro = numregistro;
	}

	public Variable(int numregistro, BigDecimal preciodolarven, Date fechaini,
			Date fechafin) {
		this.numregistro = numregistro;
		this.preciodolarven = preciodolarven;
		this.fechaini = fechaini;
		this.fechafin = fechafin;
	}

	@Id
	@Column(name = "numregistro", unique = true, nullable = false)
	public int getNumregistro() {
		return this.numregistro;
	}

	public void setNumregistro(int numregistro) {
		this.numregistro = numregistro;
	}

	@Column(name = "preciodolarven", precision = 4)
	public BigDecimal getPreciodolarven() {
		return this.preciodolarven;
	}

	public void setPreciodolarven(BigDecimal preciodolarven) {
		this.preciodolarven = preciodolarven;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaini", length = 22)
	public Date getFechaini() {
		return this.fechaini;
	}

	public void setFechaini(Date fechaini) {
		this.fechaini = fechaini;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechafin", length = 22)
	public Date getFechafin() {
		return this.fechafin;
	}

	public void setFechafin(Date fechafin) {
		this.fechafin = fechafin;
	}

}
