package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VistaactivacionesId generated by hbm2java
 */
@Embeddable
public class VistaactivacionesId implements java.io.Serializable {

	private Integer consecutivo;
	private Date fecha;
	private String estado;
	private String documento;

	public VistaactivacionesId() {
	}

	public VistaactivacionesId(Integer consecutivo, Date fecha, String estado,
			String documento) {
		this.consecutivo = consecutivo;
		this.fecha = fecha;
		this.estado = estado;
		this.documento = documento;
	}

	@Column(name = "consecutivo")
	public Integer getConsecutivo() {
		return this.consecutivo;
	}

	public void setConsecutivo(Integer consecutivo) {
		this.consecutivo = consecutivo;
	}

	@Column(name = "fecha", length = 29)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "estado")
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "documento")
	public String getDocumento() {
		return this.documento;
	}

	public void setDocumento(String documento) {
		this.documento = documento;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VistaactivacionesId))
			return false;
		VistaactivacionesId castOther = (VistaactivacionesId) other;

		return ((this.getConsecutivo() == castOther.getConsecutivo()) || (this
				.getConsecutivo() != null
				&& castOther.getConsecutivo() != null && this.getConsecutivo()
				.equals(castOther.getConsecutivo())))
				&& ((this.getFecha() == castOther.getFecha()) || (this
						.getFecha() != null
						&& castOther.getFecha() != null && this.getFecha()
						.equals(castOther.getFecha())))
				&& ((this.getEstado() == castOther.getEstado()) || (this
						.getEstado() != null
						&& castOther.getEstado() != null && this.getEstado()
						.equals(castOther.getEstado())))
				&& ((this.getDocumento() == castOther.getDocumento()) || (this
						.getDocumento() != null
						&& castOther.getDocumento() != null && this
						.getDocumento().equals(castOther.getDocumento())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getConsecutivo() == null ? 0 : this.getConsecutivo()
						.hashCode());
		result = 37 * result
				+ (getFecha() == null ? 0 : this.getFecha().hashCode());
		result = 37 * result
				+ (getEstado() == null ? 0 : this.getEstado().hashCode());
		result = 37 * result
				+ (getDocumento() == null ? 0 : this.getDocumento().hashCode());
		return result;
	}

}
