package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Vistasaldodiariopromotor generated by hbm2java
 */
@Entity
@Table(name = "vistasaldodiariopromotor")
public class Vistasaldodiariopromotor implements java.io.Serializable {

	private VistasaldodiariopromotorId id;

	public Vistasaldodiariopromotor() {
	}

	public Vistasaldodiariopromotor(VistasaldodiariopromotorId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "fecha", column = @Column(name = "fecha", length = 13)),
			@AttributeOverride(name = "documento", column = @Column(name = "documento", length = 15)),
			@AttributeOverride(name = "promotor", column = @Column(name = "promotor")),
			@AttributeOverride(name = "saldoaldia", column = @Column(name = "saldoaldia", precision = 131089, scale = 0)) })
	public VistasaldodiariopromotorId getId() {
		return this.id;
	}

	public void setId(VistasaldodiariopromotorId id) {
		this.id = id;
	}

}
