package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VistasemanasanioId generated by hbm2java
 */
@Embeddable
public class VistasemanasanioId implements java.io.Serializable {

	private String numsemana;
	private Date fechaini;
	private Date fechafin;

	public VistasemanasanioId() {
	}

	public VistasemanasanioId(String numsemana, Date fechaini, Date fechafin) {
		this.numsemana = numsemana;
		this.fechaini = fechaini;
		this.fechafin = fechafin;
	}

	@Column(name = "numsemana")
	public String getNumsemana() {
		return this.numsemana;
	}

	public void setNumsemana(String numsemana) {
		this.numsemana = numsemana;
	}

	@Column(name = "fechaini", length = 13)
	public Date getFechaini() {
		return this.fechaini;
	}

	public void setFechaini(Date fechaini) {
		this.fechaini = fechaini;
	}

	@Column(name = "fechafin", length = 13)
	public Date getFechafin() {
		return this.fechafin;
	}

	public void setFechafin(Date fechafin) {
		this.fechafin = fechafin;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VistasemanasanioId))
			return false;
		VistasemanasanioId castOther = (VistasemanasanioId) other;

		return ((this.getNumsemana() == castOther.getNumsemana()) || (this
				.getNumsemana() != null
				&& castOther.getNumsemana() != null && this.getNumsemana()
				.equals(castOther.getNumsemana())))
				&& ((this.getFechaini() == castOther.getFechaini()) || (this
						.getFechaini() != null
						&& castOther.getFechaini() != null && this
						.getFechaini().equals(castOther.getFechaini())))
				&& ((this.getFechafin() == castOther.getFechafin()) || (this
						.getFechafin() != null
						&& castOther.getFechafin() != null && this
						.getFechafin().equals(castOther.getFechafin())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getNumsemana() == null ? 0 : this.getNumsemana().hashCode());
		result = 37 * result
				+ (getFechaini() == null ? 0 : this.getFechaini().hashCode());
		result = 37 * result
				+ (getFechafin() == null ? 0 : this.getFechafin().hashCode());
		return result;
	}

}
