package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Vistacuenta generated by hbm2java
 */
@Entity
@Table(name = "vistacuenta")
public class Vistacuenta implements java.io.Serializable {

	private VistacuentaId id;

	public Vistacuenta() {
	}

	public Vistacuenta(VistacuentaId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "numcuenta", column = @Column(name = "numcuenta", length = 25)),
			@AttributeOverride(name = "fecha", column = @Column(name = "fecha", length = 29)) })
	public VistacuentaId getId() {
		return this.id;
	}

	public void setId(VistacuentaId id) {
		this.id = id;
	}

}
