package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Vistaactivaciones generated by hbm2java
 */
@Entity
@Table(name = "vistaactivaciones")
public class Vistaactivaciones implements java.io.Serializable {

	private VistaactivacionesId id;

	public Vistaactivaciones() {
	}

	public Vistaactivaciones(VistaactivacionesId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "consecutivo", column = @Column(name = "consecutivo")),
			@AttributeOverride(name = "fecha", column = @Column(name = "fecha", length = 29)),
			@AttributeOverride(name = "estado", column = @Column(name = "estado")),
			@AttributeOverride(name = "documento", column = @Column(name = "documento")) })
	public VistaactivacionesId getId() {
		return this.id;
	}

	public void setId(VistaactivacionesId id) {
		this.id = id;
	}

}
