package org.domain.monedaliquidacion.entity;

// Generated 9/06/2015 03:23:02 PM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.Length;

/**
 * VistatxdiasemanaId generated by hbm2java
 */
@Embeddable
public class VistatxdiasemanaId implements java.io.Serializable {

	private Integer codigodia;
	private Integer codigomes;
	private Date fechatx;
	private BigDecimal valortxpesos;
	private String promotor;
	private String asesor;

	public VistatxdiasemanaId() {
	}

	public VistatxdiasemanaId(Integer codigodia, Integer codigomes,
			Date fechatx, BigDecimal valortxpesos, String promotor,
			String asesor) {
		this.codigodia = codigodia;
		this.codigomes = codigomes;
		this.fechatx = fechatx;
		this.valortxpesos = valortxpesos;
		this.promotor = promotor;
		this.asesor = asesor;
	}

	@Column(name = "codigodia")
	public Integer getCodigodia() {
		return this.codigodia;
	}

	public void setCodigodia(Integer codigodia) {
		this.codigodia = codigodia;
	}

	@Column(name = "codigomes")
	public Integer getCodigomes() {
		return this.codigomes;
	}

	public void setCodigomes(Integer codigomes) {
		this.codigomes = codigomes;
	}

	@Column(name = "fechatx", length = 29)
	public Date getFechatx() {
		return this.fechatx;
	}

	public void setFechatx(Date fechatx) {
		this.fechatx = fechatx;
	}

	@Column(name = "valortxpesos", precision = 10)
	public BigDecimal getValortxpesos() {
		return this.valortxpesos;
	}

	public void setValortxpesos(BigDecimal valortxpesos) {
		this.valortxpesos = valortxpesos;
	}

	@Column(name = "promotor", length = 15)
	@Length(max = 15)
	public String getPromotor() {
		return this.promotor;
	}

	public void setPromotor(String promotor) {
		this.promotor = promotor;
	}

	@Column(name = "asesor", length = 15)
	@Length(max = 15)
	public String getAsesor() {
		return this.asesor;
	}

	public void setAsesor(String asesor) {
		this.asesor = asesor;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VistatxdiasemanaId))
			return false;
		VistatxdiasemanaId castOther = (VistatxdiasemanaId) other;

		return ((this.getCodigodia() == castOther.getCodigodia()) || (this
				.getCodigodia() != null
				&& castOther.getCodigodia() != null && this.getCodigodia()
				.equals(castOther.getCodigodia())))
				&& ((this.getCodigomes() == castOther.getCodigomes()) || (this
						.getCodigomes() != null
						&& castOther.getCodigomes() != null && this
						.getCodigomes().equals(castOther.getCodigomes())))
				&& ((this.getFechatx() == castOther.getFechatx()) || (this
						.getFechatx() != null
						&& castOther.getFechatx() != null && this.getFechatx()
						.equals(castOther.getFechatx())))
				&& ((this.getValortxpesos() == castOther.getValortxpesos()) || (this
						.getValortxpesos() != null
						&& castOther.getValortxpesos() != null && this
						.getValortxpesos().equals(castOther.getValortxpesos())))
				&& ((this.getPromotor() == castOther.getPromotor()) || (this
						.getPromotor() != null
						&& castOther.getPromotor() != null && this
						.getPromotor().equals(castOther.getPromotor())))
				&& ((this.getAsesor() == castOther.getAsesor()) || (this
						.getAsesor() != null
						&& castOther.getAsesor() != null && this.getAsesor()
						.equals(castOther.getAsesor())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodigodia() == null ? 0 : this.getCodigodia().hashCode());
		result = 37 * result
				+ (getCodigomes() == null ? 0 : this.getCodigomes().hashCode());
		result = 37 * result
				+ (getFechatx() == null ? 0 : this.getFechatx().hashCode());
		result = 37
				* result
				+ (getValortxpesos() == null ? 0 : this.getValortxpesos()
						.hashCode());
		result = 37 * result
				+ (getPromotor() == null ? 0 : this.getPromotor().hashCode());
		result = 37 * result
				+ (getAsesor() == null ? 0 : this.getAsesor().hashCode());
		return result;
	}

}
